Repository parcel-bundler/parcel, pull requests merged in 2018-03, with the labels that each got.

#805 Automatically install missing dependencies, part 2
  src/Bundler.js
  src/Logger.js
  src/cli.js
  src/utils/PromiseQueue.js
  src/utils/installPackage.js
  src/utils/localRequire.js
  src/utils/pipeSpawn.js
  test/autoinstall.js
Labels: :raising_hand_woman: Feature, :rocket: Ready For Review

#966 Add support for specifying SSL certificate & key
  src/HMRServer.js
  src/Server.js
  src/cli.js
  src/utils/getCertificate.js
  test/getCertificate.js
  test/hmr.js
  test/integration/https/primary.crt
  test/integration/https/private.pem
  test/server.js
Labels: :raising_hand_woman: Feature, :speech_balloon: RFC

#831 Add GLSL assets support
  package.json
  src/Parser.js
  src/Resolver.js
  src/assets/GLSLAsset.js
  test/glsl.js
  test/integration/glsl/compiled.glsl
  test/integration/glsl/index.js
  test/integration/glsl/lib.glsl
  test/integration/glsl/local.frag
  test/integration/glsl/local.glsl
  test/integration/glsl/local.vert
  yarn.lock
Labels: :rocket: Ready For Review

#1042 Fix cache test for OS X
  test/fs-cache.js
Labels: :rocket: Ready For Review

#1051 Added Pug support from parcel-plugin-pug
  package.json
  src/Parser.js
  src/assets/PugAsset.js
  test/integration/pug-filters/.pugrc.js
  test/integration/pug-filters/index.pug
  test/integration/pug-include-extends/base.pug
  test/integration/pug-include-extends/expect.html
  test/integration/pug-include-extends/index.pug
  test/integration/pug-include-extends/other.pug
  test/integration/pug-minify/index.pug
  test/integration/pug-mixins/index.pug
  test/integration/pug-mixins/mixins.pug
  test/integration/pug-var/100x100.png
  test/integration/pug-var/index.pug
  test/integration/pug/100x100.png
  test/integration/pug/icons.svg
  test/integration/pug/index.css
  test/integration/pug/index.js
  test/integration/pug/index.pug
  test/pug.js
  yarn.lock
Labels: :raising_hand_woman: Feature

#1052 Initial vue support
  .eslintignore
  package.json
  src/Bundler.js
  src/Parser.js
  src/assets/CSSAsset.js
  src/assets/VueAsset.js
  src/builtins/hmr-runtime.js
  src/transforms/postcss.js
  test/integration/vue-basic/Basic.vue
  test/integration/vue-css-modules/App.vue
  test/integration/vue-dependencies/App.vue
  test/integration/vue-dependencies/assets/logo.png
  test/integration/vue-functional/functional.vue
  test/integration/vue-nested-components/insidecomp.vue
  test/integration/vue-nested-components/testcomp.vue
  test/integration/vue-preprocessors/pre-processors.vue
  test/integration/vue-scoped/App.vue
  test/vue.js
  yarn.lock
Labels: :memo: WIP, :raising_hand_woman: Feature, Vue

#981 Fix builtin loaders with --target=node
  .eslintrc.json
  src/Bundler.js
  src/builtins/hmr-runtime.js
  src/builtins/loaders/browser/css-loader.js
  src/builtins/loaders/browser/js-loader.js
  src/builtins/loaders/browser/wasm-loader.js
  src/builtins/loaders/node/css-loader.js
  src/builtins/loaders/node/js-loader.js
  src/builtins/loaders/node/wasm-loader.js
  src/builtins/prelude.js
  test/javascript.js
  test/rust.js
  test/utils.js
  test/wasm.js
Labels: :memo: WIP
