Repository parcel-bundler/parcel, pull requests merged in 2018-07, with the labels that each got.

#1011 fixes #933 : JSPackager deduplication now accounts for differences in absolute dependency paths
  src/packagers/JSPackager.js
  test/integration/js-different-contents/hello.js
  test/integration/js-different-contents/index.js
  test/integration/js-different-contents/world.js
  test/integration/js-same-contents-different-dependencies/hello/index.js
  test/integration/js-same-contents-different-dependencies/hello/value.js
  test/integration/js-same-contents-different-dependencies/index.js
  test/integration/js-same-contents-different-dependencies/world/index.js
  test/integration/js-same-contents-different-dependencies/world/value.js
  test/integration/js-same-contents-same-dependencies/hello1.js
  test/integration/js-same-contents-same-dependencies/hello2.js
  test/integration/js-same-contents-same-dependencies/index.js
  test/javascript.js
Labels: :bug: Bug

#1206 Fix generate names when outside of the entry directory
  src/Bundle.js
  test/integration/service-worker/a/index.js
  test/integration/service-worker/b/nested/index.js
  test/integration/service-worker/b/nested/worker-nested.js
  test/integration/service-worker/b/worker-outside.js
  test/integration/service-worker/index.js
  test/javascript.js
Labels: :clock1: Waiting

#1681 Fix import deep wildcards with tree-shaking
  src/scope-hoisting/concat.js
  test/integration/scope-hoisting/es6/import-multiple-wildcards/a.js
  test/scope-hoisting.js
Labels: 🌳 Tree Shaking

#1683 Fix tree-shaking named import on wrapped module
  src/scope-hoisting/hoist.js
  test/integration/scope-hoisting/es6/import-wrapped/a.js
  test/integration/scope-hoisting/es6/import-wrapped/b.js
  test/scope-hoisting.js
Labels: 🌳 Tree Shaking

#1737 Prevent nameclashes with internal variables
  src/scope-hoisting/concat.js
  src/scope-hoisting/shake.js
  test/integration/scope-hoisting/es6/name-clash/a.js
  test/integration/scope-hoisting/es6/name-clash/b.js
  test/scope-hoisting.js
Labels: 🌳 Tree Shaking

#1690 Support optionally bundling node_modules for --target=node
  src/Bundler.js
  src/Resolver.js
  src/builtins/index.js
  src/cli.js
  src/visitors/dependencies.js
  test/integration/resolve-entries/browser-multiple.js
  test/integration/resolve-entries/browser.js
  test/integration/resolve-entries/pkg-browser-multiple/node-entry.js
  test/integration/resolve-entries/pkg-browser-multiple/package.json
  test/integration/resolve-entries/pkg-browser-multiple/projected-browser.js
  test/integration/resolve-entries/pkg-browser-multiple/projected.js
  test/integration/resolve-entries/pkg-browser/node-module.js
  test/integration/resolve-entries/pkg-browser/package.json
  test/javascript.js
  test/resolver.js
Labels: :raising_hand_woman: Feature

#1732 HTML bundle loader
  src/Bundler.js
  src/builtins/loaders/browser/html-loader.js
  src/builtins/loaders/node/html-loader.js
  src/packagers/HTMLPackager.js
  src/packagers/Packager.js
  src/packagers/RawPackager.js
  test/integration/import-html-async/100x100.png
  test/integration/import-html-async/index.css
  test/integration/import-html-async/index.js
  test/integration/import-html-async/other.html
  test/integration/import-html-sync/100x100.png
  test/integration/import-html-sync/index.css
  test/integration/import-html-sync/index.js
  test/integration/import-html-sync/other.html
  test/javascript.js
  test/utils.js
Labels: :raising_hand_woman: Feature

#1456 Process inline styles and scripts
  src/Pipeline.js
  src/assets/CSSAsset.js
  src/assets/HTMLAsset.js
  src/transforms/htmlnano.js
  src/visitors/dependencies.js
  test/html.js
  test/integration/html-inline-coffeescript/index.html
  test/integration/html-inline-css-import/index.html
  test/integration/html-inline-css-import/test.css
  test/integration/html-inline-js-require/index.html
  test/integration/html-inline-js-require/test.js
  test/integration/html-inline-js/index.html
  test/integration/html-inline-sass/index.html
  test/integration/html-inline-styles/bg.jpg
  test/integration/html-inline-styles/img.jpg
  test/integration/html-inline-styles/index.html
Labels: :raising_hand_woman: Feature

#1766 Support array in package.json's sideEffects property
  src/Asset.js
  src/packagers/JSConcatPackager.js
  src/scope-hoisting/hoist.js
  test/graphql.js
  test/integration/scope-hoisting/es6/side-effects-array/a.js
  test/integration/scope-hoisting/es6/side-effects-array/node_modules/bar/bar.js
  test/integration/scope-hoisting/es6/side-effects-array/node_modules/bar/foo.js
  test/integration/scope-hoisting/es6/side-effects-array/node_modules/bar/index.js
  test/integration/scope-hoisting/es6/side-effects-array/node_modules/bar/package.json
  test/scope-hoisting.js
Labels: :raising_hand_woman: Feature, 🌳 Tree Shaking

#1577 get only existing package main
  src/Resolver.js
  test/integration/resolver/node_modules/package-module-fallback/main.js
  test/integration/resolver/node_modules/package-module-fallback/package.json
  test/resolver.js
Labels: :bug: Bug

#1349 Import existing sourcemaps from libraries
  src/assets/JSAsset.js
  test/graphql.js
  test/integration/sourcemap-existing/index.js
  test/integration/sourcemap-existing/sum.js
  test/integration/sourcemap-existing/sum.map
  test/integration/sourcemap-external-contents/index.js
  test/integration/sourcemap-external-contents/sum.coffee
  test/integration/sourcemap-external-contents/sum.js
  test/integration/sourcemap-external-contents/sum.map
  test/integration/sourcemap-inline/index.js
  test/integration/sourcemap-inline/sum.js
  test/sourcemaps.js
Labels: :raising_hand_woman: Feature

#1781 Use esnext target with TypeScript and scope hoist
  src/assets/TypeScriptAsset.js
Labels: TypeScript, 🌳 Tree Shaking
