Repository parcel-bundler/parcel, pull requests merged in 2018-05, with the labels that each got.

#1101 [RFC] Support source field in package.json to enable babel on symlinked modules
  src/Resolver.js
  src/transforms/babel.js
  src/utils/fs.js
  test/integration/babel-node-modules-source-unlinked/.eslintrc.json
  test/integration/babel-node-modules-source-unlinked/index.js
  test/integration/babel-node-modules-source-unlinked/node_modules/foo/index.js
  test/integration/babel-node-modules-source-unlinked/node_modules/foo/package.json
  test/integration/babel-node-modules-source-unlinked/package.json
  test/integration/babel-node-modules-source/.eslintrc.json
  test/integration/babel-node-modules-source/index.js
  test/integration/babel-node-modules-source/node_modules/foo
  test/integration/babel-node-modules-source/package.json
  test/integration/babel-node-modules-source/packages/foo/index.js
  test/integration/babel-node-modules-source/packages/foo/package.json
  test/integration/resolver/node_modules/package-alias-glob/package.json
  test/integration/resolver/node_modules/package-alias-glob/src/test.js
  test/integration/resolver/node_modules/source
  test/integration/resolver/node_modules/source-alias
  test/integration/resolver/node_modules/source-alias-glob
  test/integration/resolver/node_modules/source-not-symlinked/dist.js
  test/integration/resolver/node_modules/source-not-symlinked/package.json
  test/integration/resolver/node_modules/source-not-symlinked/source.js
  test/integration/resolver/packages/source-alias-glob/package.json
  test/integration/resolver/packages/source-alias-glob/src/test.js
  test/integration/resolver/packages/source-alias/dist.js
  test/integration/resolver/packages/source-alias/other.js
  test/integration/resolver/packages/source-alias/package.json
  test/integration/resolver/packages/source-alias/source.js
  test/integration/resolver/packages/source/dist.js
  test/integration/resolver/packages/source/package.json
  test/integration/resolver/packages/source/source.js
  test/javascript.js
  test/resolver.js
Labels: :raising_hand_woman: Feature, :speech_balloon: RFC

#1119 Add support for multiple entry points
  src/Bundle.js
  src/Bundler.js
  src/cli.js
  src/utils/bundleReport.js
  src/utils/getRootDir.js
  src/utils/getTargetEngines.js
  test/bundler.js
  test/html.js
  test/integration/multi-entry/one.html
  test/integration/multi-entry/shared.js
  test/integration/multi-entry/two.html
  test/parser.js
  test/utils.js
Labels: :raising_hand_woman: Feature

#1393 Lookup correct generated output for bundle type in RawPackager
  src/packagers/RawPackager.js
Labels: :bug: Bug

#1396 Use config.locals to render pug template
  src/assets/PugAsset.js
Labels: :bug: Bug

#1368 Put filewatcher in a worker, for better stability and performance
  package.json
  src/Bundler.js
  src/Watcher.js
  test/hmr.js
  test/watcher.js
  yarn.lock
Labels: :bug: Bug

#1362 Fix Vue asset supplemental code concatenation
  src/assets/VueAsset.js
Labels: :bug: Bug

#1335 support for sass specific import syntax
  src/assets/SASSAsset.js
  test/integration/sass-advanced-import/bar.sass
  test/integration/sass-advanced-import/foo.sass
  test/integration/sass-advanced-import/hello.sass
  test/integration/sass-advanced-import/index.sass
  test/integration/scss-import/bar.scss
  test/integration/scss-import/base.scss
  test/integration/scss-import/foo.scss
  test/integration/scss-import/index.scss
  test/sass.js
Labels: :bug: Bug

#1324 Fix absolute and tilde paths
  src/Asset.js
  test/asset.js
Labels: :bug: Bug

#1390 Make CSS assets async
  src/assets/LESSAsset.js
  src/assets/SASSAsset.js
  src/assets/StylusAsset.js
  src/utils/pipeSpawn.js
Labels: :bug: Bug
