Repository parcel-bundler/parcel, pull requests merged in 2019-03, with the labels that each got.

#2706 Flowify `@parcel/fs`
  flow-typed/npm/mkdirp_v0.5.x.js
  packages/core/cache/src/Cache.js
  packages/core/core/package.json
  packages/core/core/src/ConfigResolver.js
  packages/core/core/src/PackagerRunner.js
  packages/core/core/src/TransformerRunner.js
  packages/core/fs/.babelrc
  packages/core/fs/index.js
  packages/core/fs/package.json
  packages/core/fs/src/.babelrc
  packages/core/fs/src/fs.js
  packages/core/fs/src/index.js
  packages/core/utils/src/config.js
  packages/resolvers/default/src/DefaultResolver.js
  packages/transformers/babel/src/config.js
  yarn.lock
Labels: ✨ Parcel 2

#2708 Use @parcel/babel-register for mocha.opts across packages
  packages/core/logger/test/mocha.opts
  packages/core/watcher/test/mocha.opts
  packages/core/workers/test/mocha.opts
Labels: ✨ Parcel 2

#2714 Clean existing lints and enable recommended flowtype lints
  packages/core/core/src/AssetGraph.js
  packages/core/register/example/index.js
  packages/core/register/src/hook.js
  packages/dev/eslint-config/index.js
Labels: ✨ Parcel 2

#2722 Fix remaining v2 tests
  packages/core/parcel-bundler/test/babel-register.js
  packages/core/parcel-bundler/test/mocha.opts
  packages/core/watcher/src/child.js
  packages/core/watcher/test/changeEvent.js
  packages/core/watcher/test/errorHandling.js
  packages/core/watcher/test/fswatcher.js
  packages/dev/babel-register/index.js
Labels: ✨ Parcel 2

#2531 Fix HMR failure with js error on load, take 2
  packages/core/integration-tests/test/hmr.js
  packages/core/parcel-bundler/src/builtins/prelude.js
  packages/core/test-utils/src/utils.js
Labels: :bug: Bug, :clock1: Waiting

#2703 Flowify md5 and flow strictify Asset and BundlerRunner
  .flowconfig
  packages/core/cache/src/Cache.js
  packages/core/core/src/Asset.js
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/BundlerRunner.js
  packages/core/core/src/Dependency.js
  packages/core/core/src/TransformerRunner.js
  packages/core/utils/src/config.js
  packages/core/utils/src/md5.js
Labels: ✨ Parcel 2

#2728 Use src references for utils
  packages/bundlers/default/src/DefaultBundler.js
  packages/core/cache/package.json
  packages/core/cache/src/Cache.js
  packages/core/core/package.json
  packages/core/core/src/Asset.js
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/Config.js
  packages/core/core/src/Graph.js
  packages/core/core/src/TargetResolver.js
  packages/core/core/src/loadEnv.js
  packages/core/register/src/hook.js
  packages/core/types/index.js
  packages/core/types/unsafe.js
  packages/resolvers/default/package.json
  packages/transformers/babel/src/babel6.js
  packages/transformers/babel/src/babel7.js
  packages/transformers/babel/src/babelrc.js
  packages/transformers/js/src/visitors/dependencies.js
Labels: ✨ Parcel 2

#2735 Update transformer entries to use `src`
  packages/core/core/src/Asset.js
  packages/core/plugin/package.json
  packages/core/register/package.json
  packages/core/types/index.js
  packages/transformers/babel/package.json
  packages/transformers/js/package.json
  packages/transformers/terser/package.json
Labels: ✨ Parcel 2

#2737 Flow strictify `Asset.js`
  packages/core/core/package.json
  packages/core/core/src/Asset.js
  packages/core/core/test/Asset.test.js
  yarn.lock
Labels: ✨ Parcel 2

#2748 Fix bug with original null mappings
  packages/core/parcel-bundler/src/SourceMap.js
Labels: :bug: Bug

#2772 Parameterize Graph on `TNode`, a type of its Nodes
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/Graph.js
  packages/core/types/index.js
  packages/core/utils/src/dumpGraphToGraphViz.js
Labels: ✨ Parcel 2

#2773 Add typings for node and graph types
  packages/bundlers/default/src/DefaultBundler.js
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/Graph.js
  packages/core/types/index.js
  packages/core/types/unsafe.js
  packages/core/utils/package.json
  packages/core/utils/src/dumpGraphToGraphViz.js
  packages/runtimes/js/src/JSRuntime.js
Labels: ✨ Parcel 2

#2740 Correctly build dependency URLs (for CSS)
  packages/core/integration-tests/test/css.js
  packages/core/integration-tests/test/sass.js
  packages/core/parcel-bundler/src/Asset.js
  packages/core/parcel-bundler/src/assets/CSSAsset.js
Labels: :bug: Bug

#2751 Separate graphviz debugging and have BundleGraph subclass Graph directly
  packages/bundlers/default/src/DefaultBundler.js
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/Graph.js
  packages/core/core/src/Parcel.js
  packages/core/types/index.js
  packages/core/utils/src/dumpGraphToGraphViz.js
  packages/runtimes/js/src/JSRuntime.js
Labels: ✨ Parcel 2

#2789 Miscellaneous flow cleanup
  packages/core/cache/src/Cache.js
  packages/core/core/src/BundlerRunner.js
  packages/core/core/src/Graph.js
  packages/core/core/src/PackagerRunner.js
  packages/core/core/src/Parcel.js
  packages/core/utils/package.json
Labels: ✨ Parcel 2

#2788 Remove unnecessary await in returns from async functions
  packages/core/cache/src/Cache.js
  packages/core/core/src/Asset.js
  packages/core/core/src/Config.js
  packages/core/core/src/ConfigResolver.js
  packages/core/core/src/PackagerRunner.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/TransformerRunner.js
  packages/core/parcel-bundler/src/Resolver.js
  packages/core/parcel-bundler/src/transforms/babel/babelrc.js
  packages/core/parcel-bundler/src/utils/loadPlugins.js
  packages/core/utils/src/loadPlugins.js
  packages/core/utils/src/localRequire.js
  packages/dev/eslint-config/index.js
  packages/resolvers/default/src/DefaultResolver.js
  packages/transformers/babel/src/BabelTransformer.js
  packages/transformers/babel/src/babelrc.js
Labels: ✨ Parcel 2

#2790 Add missing package.json entries and require them
  .eslintignore
  packages/bundlers/default/package.json
  packages/core/cache/package.json
  packages/core/core/bin.js
  packages/core/core/package.json
  packages/core/core/test/TransformerRunner.test.js
  packages/core/integration-tests/package.json
  packages/core/integration-tests/test/utils.js
  packages/core/logger/package.json
  packages/core/parcel-bundler/package.json
  packages/core/parcel-bundler/src/assets/RustAsset.js
  packages/core/parcel-bundler/src/transforms/babel/config.js
  packages/core/parcel-bundler/test/autoinstall.js
  packages/core/parcel-bundler/test/utils.js
  packages/core/register/example/index.js
  packages/core/utils/package.json
  packages/core/watcher/package.json
  packages/dev/babel-preset/package.json
  packages/dev/eslint-config/index.js
  packages/dev/eslint-config/package.json
  packages/resolvers/default/package.json
  packages/transformers/babel/package.json
  packages/transformers/js/package.json
  packages/transformers/terser/package.json
  yarn.lock
Labels: ✨ Parcel 2

#2787 Cherry-pick fixes from master for flaky tests and others
  packages/core/cache/src/Cache.js
  packages/core/core/src/Asset.js
  packages/core/core/src/Config.js
  packages/core/core/src/ConfigResolver.js
  packages/core/core/src/PackagerRunner.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/TransformerRunner.js
  packages/core/parcel-bundler/src/Asset.js
  packages/core/parcel-bundler/src/Bundler.js
  packages/core/parcel-bundler/src/Resolver.js
  packages/core/parcel-bundler/src/SourceMap.js
  packages/core/parcel-bundler/src/assets/GLSLAsset.js
  packages/core/parcel-bundler/src/assets/LESSAsset.js
  packages/core/parcel-bundler/src/assets/RawAsset.js
  packages/core/parcel-bundler/src/assets/SASSAsset.js
  packages/core/parcel-bundler/src/transforms/babel/babelrc.js
  packages/core/parcel-bundler/src/utils/getModuleParts.js
  packages/core/parcel-bundler/src/utils/loadPlugins.js
  packages/core/parcel-bundler/src/utils/localRequire.js
  packages/core/parcel-bundler/test/sourcemaps.js
  packages/core/utils/src/loadPlugins.js
  packages/core/utils/src/localRequire.js
  packages/core/watcher/test/fswatcher.js
  packages/dev/eslint-config/index.js
  packages/resolvers/default/src/DefaultResolver.js
  packages/transformers/babel/src/BabelTransformer.js
  packages/transformers/babel/src/babelrc.js
  yarn.lock
Labels: ✨ Parcel 2

#2798 Remove utils dependency from fs
  packages/core/fs/package.json
Labels: ✨ Parcel 2

#2802 Flowify @parcel/workers
  flow-libs/dotenv-expand.js.flow
  flow-libs/dotenv.js.flow
  packages/core/cache/src/Cache.js
  packages/core/core/src/loadEnv.js
  packages/core/logger/src/Logger.js
  packages/core/parcel-bundler/src/Bundler.js
  packages/core/parcel-bundler/src/utils/installPackage.js
  packages/core/types/index.js
  packages/core/utils/getRootDir.js
  packages/core/utils/serializer.js
  packages/core/utils/src/localRequire.js
  packages/core/workers/index.js
  packages/core/workers/package.json
  packages/core/workers/src/.babelrc
  packages/core/workers/src/Worker.js
  packages/core/workers/src/WorkerFarm.js
  packages/core/workers/src/child.js
  packages/core/workers/src/types.js
  packages/core/workers/test/integration/workerfarm/ipc-pid.js
  packages/core/workers/test/integration/workerfarm/ipc.js
  packages/core/workers/test/workerfarm.js
Labels: ✨ Parcel 2

#2806 Remove unnecessary assertion
  packages/core/workers/src/child.js
Labels: ✨ Parcel 2

#2800 Flowify @parcel/logger
  flow-libs/abortcontroller-polyfill.js.flow
  flow-libs/grapheme-breaker.js.flow
  flow-libs/ora.js.flow
  flow-libs/strip-ansi.js.flow
  packages/core/logger/index.js
  packages/core/logger/package.json
  packages/core/logger/src/.babelrc
  packages/core/logger/src/Logger.js
  packages/core/logger/src/emoji.js
  packages/core/logger/src/prettyError.js
  packages/core/logger/test/logger.js
  packages/core/logger/test/prettyError.js
  packages/core/parcel-bundler/src/Asset.js
  packages/core/parcel-bundler/src/Bundler.js
  packages/core/parcel-bundler/src/FSCache.js
  packages/core/parcel-bundler/src/HMRServer.js
  packages/core/parcel-bundler/src/Server.js
  packages/core/parcel-bundler/src/assets/JSAsset.js
  packages/core/parcel-bundler/src/assets/JSONLDAsset.js
  packages/core/parcel-bundler/src/transforms/babel/babelrc.js
  packages/core/parcel-bundler/src/utils/bundleReport.js
  packages/core/parcel-bundler/src/utils/generateCertificate.js
  packages/core/parcel-bundler/src/utils/installPackage.js
  packages/core/parcel-bundler/src/utils/pipeSpawn.js
  packages/core/parcel-bundler/src/visitors/fs.js
  packages/core/utils/src/installPackage.js
  packages/core/utils/src/pipeSpawn.js
  packages/core/utils/src/prettyError.js
Labels: ✨ Parcel 2

#2814 Flowify @parcel/utils
  .flowconfig
  flow-libs/fast-glob.js.flow
  flow-libs/resolve.js.flow
  flow-typed/npm/is-url_v1.x.x.js
  packages/core/cache/src/Cache.js
  packages/core/core/src/Config.js
  packages/core/core/src/ConfigResolver.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/PromiseQueue.js
  packages/core/integration-tests/test/utils.js
  packages/core/parcel-bundler/src/Bundler.js
  packages/core/parcel-bundler/src/assets/GLSLAsset.js
  packages/core/parcel-bundler/src/assets/LESSAsset.js
  packages/core/parcel-bundler/src/assets/RustAsset.js
  packages/core/parcel-bundler/src/assets/SASSAsset.js
  packages/core/parcel-bundler/src/packagers/Packager.js
  packages/core/parcel-bundler/src/utils/installPackage.js
  packages/core/parcel-bundler/src/utils/localRequire.js
  packages/core/parcel-bundler/test/utils.js
  packages/core/types/index.js
  packages/core/utils/index.js
  packages/core/utils/package.json
  packages/core/utils/src/bundle-url.js
  packages/core/utils/src/errorUtils.js
  packages/core/utils/src/getExisting.js
  packages/core/utils/src/getRootDir.js
  packages/core/utils/src/glob.js
  packages/core/utils/src/index.js
  packages/core/utils/src/installPackage.js
  packages/core/utils/src/is-url.js
  packages/core/utils/src/localRequire.js
  packages/core/utils/src/resolve.js
  packages/core/utils/src/serializer.js
  packages/core/watcher/src/Watcher.js
  packages/core/watcher/src/child.js
  packages/core/workers/src/Worker.js
  packages/core/workers/src/WorkerFarm.js
  packages/core/workers/src/child.js
  packages/core/workers/src/types.js
  packages/dev/eslint-config/index.js
  packages/resolvers/default/src/DefaultResolver.js
  packages/transformers/babel/src/babelrc.js
Labels: ✨ Parcel 2

#2702 Unify build abort errors
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/Parcel.js
  packages/core/core/test/AssetGraphBuilder.test.js
  packages/resolvers/default/src/DefaultResolver.js
Labels: ✨ Parcel 2

#2815 Flowify Watcher
  flow-libs/chokidar.js.flow
  packages/core/watcher/.babelrc
  packages/core/watcher/index.js
  packages/core/watcher/package.json
  packages/core/watcher/src/Watcher.js
  packages/core/watcher/src/child.js
  packages/core/watcher/src/options.js
  packages/core/watcher/test/changeEvent.js
  packages/core/watcher/test/errorHandling.js
  packages/core/watcher/test/fswatcher.js
  packages/core/watcher/test/options.js
  packages/core/watcher/test/watched.js
Labels: ✨ Parcel 2

#2828 Flowify more utils
  flow-libs/cross-spawn.js.flow
  flow-libs/deasync.js
  flow-libs/serialize-to-js.js.flow
  flow-libs/terser.js.flow
  packages/core/utils/package.json
  packages/core/utils/src/PromiseQueue.js
  packages/core/utils/src/installPackage.js
  packages/core/utils/src/lineCounter.js
  packages/core/utils/src/loadPlugins.js
  packages/core/utils/src/objectHash.js
  packages/core/utils/src/parseCSSImport.js
  packages/core/utils/src/prettifyTime.js
  packages/core/utils/src/serializeObject.js
  packages/core/utils/src/syncPromise.js
  packages/core/utils/src/urlJoin.js
  packages/transformers/terser/package.json
  packages/transformers/terser/src/TerserTransformer.js
Labels: ✨ Parcel 2

#2827 Centralize eslint configuration
  packages/core/cache/.eslintrc.json
  packages/core/core/.eslintrc.json
  packages/core/core/test/.eslintrc.json
  packages/core/integration-tests/test/.eslintrc.json
  packages/core/logger/test/.eslintrc.json
  packages/core/plugin/.eslintrc.json
  packages/core/utils/src/.eslintrc.json
  packages/core/watcher/test/.eslintrc.json
  packages/core/workers/src/.eslintrc.json
  packages/core/workers/test/.eslintrc.json
  packages/dev/eslint-config/index.js
  packages/packagers/js/.eslintrc.json
  packages/reporters/cli/.eslintrc
  packages/reporters/cli/package.json
  packages/reporters/cli/test/.eslintrc
  packages/transformers/babel/.eslintrc.json
  packages/transformers/css/.eslintrc.json
  packages/transformers/js/.eslintrc.json
  packages/transformers/terser/.eslintrc.json
Labels: ✨ Parcel 2

#2825 Flowify cli reporter
  flow-libs/cli-spinners.js.flow
  flow-libs/ink.js.flow
  packages/core/types/index.js
  packages/core/utils/src/prettifyTime.js
  packages/reporters/cli/.babelrc
  packages/reporters/cli/package.json
  packages/reporters/cli/src/BundleReport.js
  packages/reporters/cli/src/CLIReporter.js
  packages/reporters/cli/src/Log.js
  packages/reporters/cli/src/Spinner.js
  packages/reporters/cli/src/Table.js
  packages/reporters/cli/src/UI.js
  packages/reporters/cli/src/emoji.js
  packages/reporters/cli/test/mocha.opts
Labels: ✨ Parcel 2

#2771 Allow @scope/parcel-<kind> as a valid plugin name
  PARCEL_2_RFC.md
Labels: ✨ Parcel 2

#2832 Merge react eslint rules into main config
  packages/core/is-v2-ready-yet/.eslintrc
  packages/core/is-v2-ready-yet/package.json
  packages/core/is-v2-ready-yet/src/Footer.js
  packages/core/is-v2-ready-yet/src/HeatMap.js
  packages/core/parcel-bundler/src/Bundler.js
  packages/dev/eslint-config/index.js
  packages/reporters/cli/.eslintrc
  packages/reporters/cli/src/BundleReport.js
Labels: ✨ Parcel 2

#2849 Implement a simple CLI reporter for non-TTYs
  packages/core/parcel/package.json
  packages/reporters/cli/package.json
  packages/reporters/cli/src/BundleReport.js
  packages/reporters/cli/src/CLIReporter.js
  packages/reporters/cli/src/SimpleCLIReporter.js
  packages/reporters/cli/src/UI.js
  packages/reporters/cli/src/index.js
  packages/reporters/cli/src/logLevels.js
  packages/reporters/cli/src/utils.js
  packages/reporters/cli/test/SimpleCLIReporter.test.js
  yarn.lock
Labels: ✨ Parcel 2

#2860 Remove old cli interface and update simple example
  packages/core/core/bin.js
  packages/core/core/package.json
  packages/examples/simple/package.json
Labels: ✨ Parcel 2

#2854 @parcel/config-default: Require referenced modules as dependencies
  packages/configs/default/package.json
  packages/configs/default/test/.babelrc
  packages/configs/default/test/config.test.js
  packages/configs/default/test/mocha.opts
Labels: ✨ Parcel 2
