Repository parcel-bundler/parcel, pull requests merged in 2019-05, with the labels that each got.

#2972 Naming and targets refactor
  package.json
  packages/core/cache/src/Cache.js
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/BundlerRunner.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/ReporterRunner.js
  packages/core/core/src/ResolverRunner.js
  packages/core/core/src/TargetResolver.js
  packages/core/core/src/public/Bundle.js
  packages/core/core/src/public/MainAssetGraph.js
  packages/core/core/src/resolveOptions.js
  packages/core/core/src/types.js
  packages/core/core/test/AssetGraph.test.js
  packages/core/core/test/AssetGraphBuilder.test.js
  packages/core/core/test/TransformerRunner.test.js
  packages/core/integration-tests/test/javascript.js
  packages/core/integration-tests/test/server.js
  packages/core/parcel/src/cli.js
  packages/core/types/index.js
  packages/core/utils/src/path.js
  packages/namers/default/package.json
  packages/namers/default/src/DefaultNamer.js
  packages/reporters/cli/test/SimpleCLIReporter.test.js
  packages/reporters/dev-server/src/ServerReporter.js
  packages/reporters/hmr-server/src/HMRReporter.js
  packages/reporters/hmr-server/src/types.js.flow
  packages/resolvers/default/src/DefaultResolver.js
  packages/runtimes/js/src/JSRuntime.js
Labels: ✨ Parcel 2

#2875 Replace module.require in scope hoisting
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/module-object/a.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/parcel-bundler/src/scope-hoisting/hoist.js
Labels: 🌳 Tree Shaking

#2993 Define __esModule interop flag when requiring ES module from CommonJS
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module/b.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/parcel-bundler/src/Asset.js
  packages/core/parcel-bundler/src/builtins/helpers.js
  packages/core/parcel-bundler/src/scope-hoisting/concat.js
Labels: 🌳 Tree Shaking

#2997 Update to flow 0.98.1
  .flowconfig
  package.json
  packages/core/fs/src/index.js
  yarn.lock
Labels: ✨ Parcel 2

#2994 Fix assigning to exports from inside a function in scope hoisting
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/export-assign-scope/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/export-assign-scope/b.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/parcel-bundler/src/scope-hoisting/hoist.js
Labels: 🌳 Tree Shaking

#3015 Exit with a code of 1 for failures outside watch
  packages/core/core/src/Parcel.js
  packages/core/core/src/resolveOptions.js
  packages/core/core/test/AssetGraphBuilder.test.js
  packages/core/core/test/TransformerRunner.test.js
  packages/core/parcel/src/cli.js
  packages/core/test-utils/src/utils.js
  packages/core/types/index.js
  packages/reporters/cli/src/SimpleCLIReporter.js
  packages/reporters/cli/test/SimpleCLIReporter.test.js
Labels: ✨ Parcel 2

#3013 Make Some Core Parcel API Private
  flow-libs/ncp.js.flow
  packages/core/core/src/Parcel.js
  packages/core/fs/package.json
  packages/core/fs/src/index.js
  packages/core/integration-tests/test/server.js
Labels: ✨ Parcel 2

#3039 Add source-map types from flow-typed and integrate them
  flow-typed/npm/source-map_v0.7.x.js
  packages/core/source-map/src/SourceMap.js
Labels: ✨ Parcel 2

#3038 Prevent relative cross-package imports with eslint-plugin-monorepo
  packages/core/is-v2-ready-yet/.eslintrc
  packages/dev/eslint-config/index.js
  packages/dev/eslint-config/package.json
  yarn.lock
Labels: ✨ Parcel 2

#3044 Restore webp to raw globs in default config
  packages/configs/default/index.json
Labels: ✨ Parcel 2

#3036 CSSPackager: Apply CSS Styles in the correct order
  packages/core/integration-tests/test/css.js
  packages/core/integration-tests/test/integration/css-order/a.css
  packages/core/integration-tests/test/integration/css-order/b.css
  packages/core/integration-tests/test/integration/css-order/c.css
  packages/core/integration-tests/test/integration/css-order/d.css
  packages/core/integration-tests/test/integration/css-order/e.css
  packages/packagers/css/src/CSSPackager.js
Labels: ✨ Parcel 2

#3054 Remove unused dependencies from core package.json
  packages/core/core/package.json
Labels: ✨ Parcel 2

#3065 New AssetGraph
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/Graph.js
  packages/core/core/src/OldAssetGraph.js
  packages/core/core/src/dumpGraphToGraphViz.js
  packages/core/core/src/types.js
  packages/core/core/test/AssetGraph.test.js
  packages/core/types/index.js
Labels: ✨ Parcel 2

#3072 Rename package versions to 2.0.0-alpha.0
  packages/bundlers/default/package.json
  packages/configs/default/package.json
  packages/core/cache/package.json
  packages/core/core/package.json
  packages/core/fs/package.json
  packages/core/install-package/package.json
  packages/core/integration-tests/package.json
  packages/core/is-v2-ready-yet/package.json
  packages/core/local-require/package.json
  packages/core/logger/package.json
  packages/core/parcel-bundler/package.json
  packages/core/parcel/package.json
  packages/core/plugin/package.json
  packages/core/register/example/package.json
  packages/core/register/package.json
  packages/core/test-utils/package.json
  packages/core/types/package.json
  packages/core/utils/package.json
  packages/core/workers/package.json
  packages/dev/babel-preset/package.json
  packages/dev/babel-register/package.json
  packages/dev/eslint-config-browser/package.json
  packages/dev/eslint-config/package.json
  packages/dev/eslint-plugin/package.json
  packages/examples/html/package.json
  packages/examples/kitchen-sink/package.json
  packages/examples/react-hmr/package.json
  packages/examples/simple/package.json
  packages/namers/default/package.json
  packages/packagers/css/package.json
  packages/packagers/html/package.json
  packages/packagers/js/package.json
  packages/packagers/raw/package.json
  packages/reporters/cli/package.json
  packages/reporters/dev-server/package.json
  packages/reporters/hmr-server/package.json
  packages/reporters/json/package.json
  packages/resolvers/default/package.json
  packages/runtimes/hmr/package.json
  packages/runtimes/js/package.json
  packages/shared/scope-hoisting/package.json
  packages/transformers/babel/package.json
  packages/transformers/css/package.json
  packages/transformers/html/package.json
  packages/transformers/js/package.json
  packages/transformers/postcss/package.json
  packages/transformers/raw/package.json
  packages/transformers/terser/package.json
  packages/utils/events/package.json
Labels: ✨ Parcel 2

#3077 Add a missing clearScope to hoisting
  packages/core/integration-tests/test/integration/scope-hoisting/es6/class-selfreference/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/class-selfreference/package.json
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/hoist.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#2742 Scope hoisting destructuring
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-array/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-array/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-array/package.json
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-object/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-object/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-object/package.json
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/parcel-bundler/src/packagers/JSConcatPackager.js
Labels: :bug: Bug

#3082 Requeue inserted globals when hoisting
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/globals-polyfills/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/globals-polyfills/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/globals-polyfills/package.json
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/hoist.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#3084 Scope hoisting destructuring
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-array/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-array/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-array/package.json
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-object/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-object/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-object/package.json
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/concat.js
Labels: ✨ Parcel 2

#3079 Introduce RequestGraph to help build skinny AssetGraph
  packages/core/core/src/Asset.js
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/BundlerRunner.js
  packages/core/core/src/Graph.js
  packages/core/core/src/OldAssetGraph.js
  packages/core/core/src/RequestGraph.js
  packages/core/core/src/ResolverRunner.js
  packages/core/core/src/TransformerRunner.js
  packages/core/core/src/dumpGraphToGraphViz.js
  packages/core/core/src/types.js
  packages/core/core/src/worker.js
  packages/core/core/test/AssetGraph.test.js
  packages/core/core/test/AssetGraphBuilder.test.js
  packages/core/integration-tests/test/server.js
  packages/core/types/index.js
  packages/core/utils/src/PromiseQueue.js
  packages/core/utils/test/PromiseQueue.test.js
  packages/resolvers/default/src/DefaultResolver.js
Labels: ✨ Parcel 2

#3069 CSSNano optimizer
  packages/configs/default/index.json
  packages/core/core/src/PackagerRunner.js
  packages/core/integration-tests/test/css.js
  packages/core/utils/src/index.js
  packages/core/utils/src/urlRelative.js
  packages/optimizers/cssnano/package.json
  packages/optimizers/cssnano/src/CSSNanoOptimizer.js
  yarn.lock
Labels: ✨ Parcel 2

#3092 Use fsStream.bytesWritten
  packages/core/core/src/PackagerRunner.js
  packages/core/fs/src/index.js
Labels: ✨ Parcel 2

#3088 Add missing engines
  packages/bundlers/default/package.json
  packages/core/cache/package.json
  packages/core/plugin/package.json
  packages/core/register/package.json
  packages/packagers/css/package.json
  packages/packagers/html/package.json
  packages/packagers/js/package.json
  packages/packagers/raw/package.json
  packages/reporters/cli/package.json
  packages/reporters/json/package.json
  packages/runtimes/hmr/package.json
  packages/runtimes/js/package.json
  packages/transformers/babel/package.json
  packages/transformers/css/package.json
  packages/transformers/html/package.json
  packages/transformers/js/package.json
  packages/transformers/postcss/package.json
  packages/transformers/raw/package.json
  packages/transformers/terser/package.json
  packages/utils/events/package.json
Labels: ✨ Parcel 2

#3103 Add Disposable
  packages/utils/events/src/Disposable.js
  packages/utils/events/src/index.js
  packages/utils/events/test/Disposable.test.js
Labels: ✨ Parcel 2

#3063 Parcel v2: PostHTML transformer
  flow-libs/posthtml.js.flow
  packages/configs/default/index.json
  packages/configs/default/package.json
  packages/core/integration-tests/test/posthtml.js
  packages/transformers/html/.eslintrc.json
  packages/transformers/posthtml/package.json
  packages/transformers/posthtml/src/PostHTMLTransformer.js
  packages/transformers/posthtml/src/loadPlugins.js
  yarn.lock
Labels: ✨ Parcel 2, 🔌 Parcel 2 Plugins

#3102 Add reverse handle functionality to WorkerFarm
  packages/core/core/src/Parcel.js
  packages/core/core/src/RequestGraph.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/workers/src/Handle.js
  packages/core/workers/src/WorkerFarm.js
  packages/core/workers/src/child.js
  packages/core/workers/src/types.js
  packages/core/workers/test/integration/workerfarm/reverse-handle.js
  packages/core/workers/test/workerfarm.js
Labels: ✨ Parcel 2

#3099 Pass minimum versions to @babel/preset-env
  packages/core/integration-tests/test/babel.js
  packages/core/integration-tests/test/integration/babel-semver-engine/foo.js
  packages/core/integration-tests/test/integration/babel-semver-engine/index.js
  packages/core/integration-tests/test/integration/babel-semver-engine/package.json
  packages/transformers/babel/src/env.js
  packages/transformers/babel/src/getTargetEngines.js
Labels: ✨ Parcel 2

#3089 Implement basic json transformer
  packages/configs/default/index.json
  packages/configs/default/package.json
  packages/core/integration-tests/test/javascript.js
  packages/transformers/json/.babelrc
  packages/transformers/json/package.json
  packages/transformers/json/src/JSONTransformer.js
Labels: ✨ Parcel 2

#3047 Resolve option file paths as absolute
  packages/core/core/src/Parcel.js
  packages/core/core/src/TargetResolver.js
  packages/core/core/src/resolveOptions.js
  packages/core/integration-tests/test/server.js
Labels: ✨ Parcel 2

#3119 Fix test from bad integration
  packages/core/integration-tests/test/babel.js
Labels: ✨ Parcel 2
