Repository parcel-bundler/parcel, pull requests merged in 2019-01, with the labels that each got.

#2440 Parcel 2: Add CSS transformer
  packages/configs/default/index.json
  packages/configs/default/package.json
  packages/core/types/index.js
  packages/examples/simple/src/child.css
  packages/examples/simple/src/index.js
  packages/examples/simple/src/styles.css
  packages/resolvers/default/src/DefaultResolver.js
  packages/transformers/css/.eslintrc.json
  packages/transformers/css/package.json
  packages/transformers/css/src/CSSTransformer.js
  yarn.lock
Labels: ✨ Parcel 2, 🔌 Parcel 2 Plugins

#2518 addURLDependency: use always relative path
  packages/core/integration-tests/test/css.js
  packages/core/integration-tests/test/integration/css-url-relative/src/a/style1.css
  packages/core/integration-tests/test/integration/css-url-relative/src/b/style2.css
  packages/core/integration-tests/test/integration/css-url-relative/src/foo.png
  packages/core/parcel-bundler/src/Asset.js
Labels: :bug: Bug

#2522 Parcel 2: Serializer for complex object types
  packages/bundlers/default/src/DefaultBundler.js
  packages/core/cache/src/Cache.js
  packages/core/core/src/Asset.js
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/Dependency.js
  packages/core/core/src/Environment.js
  packages/core/core/src/Graph.js
  packages/core/core/src/PackagerRunner.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/TargetResolver.js
  packages/core/core/src/TransformerRunner.js
  packages/core/core/src/createDependency.js
  packages/core/core/src/worker.js
  packages/core/core/test/AssetGraph.test.js
  packages/core/core/test/TransformerRunner.test.js
  packages/core/parcel-bundler/src/Bundler.js
  packages/core/parcel-bundler/src/assets/VueAsset.js
  packages/core/parcel-bundler/test/utils.js
  packages/core/types/index.js
  packages/core/utils/serializer.js
  packages/core/workers/src/Worker.js
  packages/core/workers/src/child.js
  packages/dev/babel-preset/common.js
  packages/dev/babel-preset/serializer.js
  packages/resolvers/default/src/DefaultResolver.js
  packages/transformers/css/src/CSSTransformer.js
  packages/transformers/js/src/JSTransformer.js
Labels: ✨ Parcel 2

#2491 re-exporting and renaming when scopehoisting
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-renamed/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-renamed/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-renamed/c.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/parcel-bundler/src/scope-hoisting/renamer.js
Labels: :bug: Bug

#2485 added fix for typescript asset invalidation
  packages/core/parcel-bundler/src/assets/JSAsset.js
  packages/core/parcel-bundler/src/assets/TypeScriptAsset.js
  packages/core/parcel-bundler/src/utils/isAccessedVarChanged.js
Labels: :bug: Bug

#2534 Parcel 2: Runtime plugins and bundle loader support
  packages/bundlers/default/src/DefaultBundler.js
  packages/configs/default/index.json
  packages/core/core/src/Asset.js
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/BundlerRunner.js
  packages/core/core/src/Config.js
  packages/core/core/src/Graph.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/TransformerRunner.js
  packages/core/integration-tests/test/integration/dynamic-common-large/a.js
  packages/core/integration-tests/test/integration/dynamic-common-large/b.js
  packages/core/integration-tests/test/integration/dynamic-common-large/common.js
  packages/core/integration-tests/test/integration/dynamic-common-large/index.js
  packages/core/integration-tests/test/integration/dynamic-common-small/a.js
  packages/core/integration-tests/test/integration/dynamic-common-small/b.js
  packages/core/integration-tests/test/integration/dynamic-common-small/common-dep.js
  packages/core/integration-tests/test/integration/dynamic-common-small/common.js
  packages/core/integration-tests/test/integration/dynamic-common-small/index.js
  packages/core/integration-tests/test/integration/dynamic-node/index.js
  packages/core/integration-tests/test/integration/dynamic-node/local.js
  packages/core/integration-tests/test/integration/dynamic-node/package.json
  packages/core/integration-tests/test/javascript.js
  packages/core/integration-tests/test/utils.js
  packages/core/plugin/src/PluginAPI.js
  packages/core/types/index.js
  packages/packagers/js/src/JSPackager.js
  packages/runtimes/js/package.json
  packages/runtimes/js/src/JSRuntime.js
  packages/runtimes/js/src/bundle-loader.js
  packages/runtimes/js/src/bundle-url.js
  packages/runtimes/js/src/loaders/.eslintrc.json
  packages/runtimes/js/src/loaders/browser/css-loader.js
  packages/runtimes/js/src/loaders/browser/html-loader.js
  packages/runtimes/js/src/loaders/browser/js-loader.js
  packages/runtimes/js/src/loaders/browser/wasm-loader.js
  packages/runtimes/js/src/loaders/node/css-loader.js
  packages/runtimes/js/src/loaders/node/html-loader.js
  packages/runtimes/js/src/loaders/node/js-loader.js
  packages/runtimes/js/src/loaders/node/wasm-loader.js
  packages/transformers/babel/src/env.js
  packages/transformers/js/src/JSTransformer.js
  packages/transformers/js/src/visitors/dependencies.js
  packages/transformers/js/src/visitors/globals.js
  packages/transformers/js/src/visitors/utils.js
Labels: ✨ Parcel 2, 🔌 Parcel 2 Plugins
