Repository parcel-bundler/parcel, pull requests merged in 2019-08, with the labels that each got.

#3297 Config: resolve all entries and rootDir to absolute paths
  packages/core/core/src/resolveOptions.js
Labels: ✨ Parcel 2

#3309 Copy devserver templates during build
  gulpfile.js
Labels: ✨ Parcel 2

#3316 Speedup validations
  packages/core/core/src/RequestGraph.js
  packages/core/core/src/Validation.js
Labels: ✨ Parcel 2

#3328 Don't create shared bundles from entry bundles
  packages/bundlers/default/src/DefaultBundler.js
  packages/core/integration-tests/test/integration/no-shared-bundles-from-entries/a.js
  packages/core/integration-tests/test/integration/no-shared-bundles-from-entries/b.js
  packages/core/integration-tests/test/integration/no-shared-bundles-from-entries/package.json
  packages/core/integration-tests/test/javascript.js
Labels: ✨ Parcel 2

#3331 Insert sibling bundle references into HTML
  packages/core/integration-tests/test/html.js
  packages/packagers/html/package.json
  packages/packagers/html/src/HTMLPackager.js
  packages/transformers/html/src/HTMLTransformer.js
Labels: ✨ Parcel 2

#3343 Random v2 cleanup
  packages/core/fs/src/NodeFS.js
  packages/core/parcel-bundler/package.json
  packages/core/parcel/package.json
  packages/examples/html/package.json
  packages/examples/kitchen-sink/package.json
  packages/examples/react-hmr/package.json
  packages/examples/simple/package.json
  packages/examples/ts-example/package.json
  packages/examples/ts-typecheck-example/.parcelrc
  packages/examples/ts-typecheck-example/package.json
  packages/reporters/cli/src/SimpleCLIReporter.js
  packages/transformers/typescript-tsc/package.json
  packages/validators/typescript/.babelrc
  packages/validators/typescript/package.json
  packages/validators/typescript/src/TypeScriptValidator.js
  packages/validators/typescript/src/formatDiagnostics.js
  packages/validators/typescript/src/languageServiceHost.js
Labels: ✨ Parcel 2

#3344 Limit concurrency when reading assets in packagers
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/RequestGraph.js
  packages/core/utils/src/PromiseQueue.js
  packages/packagers/css/package.json
  packages/packagers/css/src/CSSPackager.js
  packages/packagers/js/src/JSPackager.js
  packages/shared/scope-hoisting/package.json
  packages/shared/scope-hoisting/src/concat.js
Labels: ✨ Parcel 2

#3350 Ensure that HMR runtime is added as an entry to the bundle
  packages/core/core/src/BundlerRunner.js
  packages/core/core/src/PackagerRunner.js
  packages/core/core/src/public/Bundle.js
  packages/core/core/src/public/BundlerBundleGraph.js
  packages/core/core/src/types.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/test-utils/src/utils.js
  packages/core/types/index.js
  packages/namers/default/src/DefaultNamer.js
  packages/packagers/js/src/JSPackager.js
  packages/runtimes/hmr/src/HMRRuntime.js
  packages/runtimes/js/src/JSRuntime.js
  packages/shared/scope-hoisting/src/concat.js
  packages/shared/scope-hoisting/src/generate.js
Labels: ✨ Parcel 2

#3346 Add --profile option for multi threaded profiling
  flow-libs/chrome-trace-event.js.flow
  flow-libs/inspector.js.flow
  packages/core/core/src/Parcel.js
  packages/core/core/src/resolveOptions.js
  packages/core/core/src/types.js
  packages/core/core/test/utils.js
  packages/core/parcel/src/cli.js
  packages/core/types/index.js
  packages/core/workers/package.json
  packages/core/workers/src/Profiler.js
  packages/core/workers/src/Trace.js
  packages/core/workers/src/WorkerFarm.js
  packages/core/workers/src/child.js
  yarn.lock
Labels: ✨ Parcel 2

#3371 Default to ending WorkerFarm
  packages/core/core/src/resolveOptions.js
Labels: ✨ Parcel 2

#3373 Allow --no-scope-hoist as a cli option for builds
  packages/core/parcel/src/cli.js
Labels: ✨ Parcel 2

#3167 `parcelRequire is not defined`
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/integration-tests/test/html.js
  packages/core/integration-tests/test/integration/html-js-dynamic/index.html
  packages/core/integration-tests/test/integration/html-js-dynamic/index.js
  packages/core/integration-tests/test/integration/html-js-dynamic/local.js
  packages/core/integration-tests/test/integration/html-js/index.html
  packages/core/integration-tests/test/integration/html-js/index.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/test-utils/src/utils.js
  packages/core/types/index.js
  packages/shared/scope-hoisting/src/concat.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#3320 Remove WorkerFarm singleton
  .mocharc.json
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/BundlerRunner.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/RequestGraph.js
  packages/core/core/src/Transformation.js
  packages/core/core/src/Validation.js
  packages/core/core/src/index.js
  packages/core/core/src/worker.js
  packages/core/core/test/AssetGraphBuilder.test.js
  packages/core/fs/src/MemoryFS.js
  packages/core/install-package/src/installPackage.js
  packages/core/integration-tests/.mocharc.json
  packages/core/integration-tests/package.json
  packages/core/integration-tests/test/mocha.opts
  packages/core/integration-tests/test/postcss.js
  packages/core/local-require/src/localRequire.js
  packages/core/test-utils/src/mochaSetup.js
  packages/core/test-utils/src/utils.js
  packages/core/types/index.js
  packages/core/utils/test/PromiseQueue.test.js
  packages/core/workers/src/Handle.js
  packages/core/workers/src/WorkerFarm.js
  packages/core/workers/src/bus.js
  packages/core/workers/src/child.js
  packages/core/workers/src/index.js
  packages/core/workers/src/types.js
  packages/core/workers/test/integration/workerfarm/echo.js
  packages/core/workers/test/integration/workerfarm/ipc-pid.js
  packages/core/workers/test/integration/workerfarm/ipc.js
  packages/core/workers/test/integration/workerfarm/reverse-handle.js
  packages/core/workers/test/workerfarm.js
  packages/transformers/babel/src/BabelTransformer.js
  packages/transformers/babel/src/babel6.js
  packages/transformers/babel/src/babel7.js
  packages/transformers/postcss/src/PostCSSTransformer.js
  packages/transformers/postcss/src/loadPlugins.js
  packages/transformers/posthtml/src/PostHTMLTransformer.js
  packages/transformers/posthtml/src/loadPlugins.js
  packages/transformers/stylus/src/StylusTransformer.js
  packages/transformers/typescript-tsc/src/TSCTransformer.js
  packages/validators/typescript/src/TypeScriptValidator.js
  yarn.lock
Labels: ✨ Parcel 2

#3381 Pass bound localRequire to validators
  packages/core/core/src/Validation.js
Labels: ✨ Parcel 2

#3386 Add toml transformer and make test pass
  packages/configs/default/index.json
  packages/configs/default/package.json
  packages/core/integration-tests/test/javascript.js
  packages/transformers/toml/package.json
  packages/transformers/toml/src/TOMLTransformer.js
Labels: ✨ Parcel 2, 🔌 Parcel 2 Plugins

#3383 Inline and DCE process.env.PARCEL_BUILD_ENV and fix Linux dev env
  gulpfile.js
  package.json
  packages/core/parcel/package.json
  packages/core/parcel/src/bin.js
  packages/dev/babel-preset/index.js
  packages/dev/babel-preset/package.json
  yarn.lock
Labels: ✨ Parcel 2

#3405 Fix mismatching ids in request and asset graph
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/RequestGraph.js
  packages/core/integration-tests/test/watcher.js
Labels: ✨ Parcel 2

#3367 Throw user friendly errors if resolver detects webpack load imports
  packages/core/integration-tests/test/integration/webpack-import-syntax-error/index.js
  packages/core/integration-tests/test/integration/webpack-import-syntax-error/package.json
  packages/core/integration-tests/test/resolver.js
  packages/resolvers/default/src/DefaultResolver.js
Labels: ✨ Parcel 2

#3395 V2: SugarSS transformer
  packages/configs/default/index.json
  packages/configs/default/package.json
  packages/core/integration-tests/test/sugarss.js
  packages/transformers/sugarss/package.json
  packages/transformers/sugarss/src/SugarssTransformer.js
Labels: ✨ Parcel 2, 🔌 Parcel 2 Plugins

#3340 Add getConfig to Validator Plugins
  packages/core/core/src/Validation.js
  packages/core/types/index.js
  packages/validators/typescript/src/TypeScriptValidator.js
Labels: ✨ Parcel 2

#3353 V2: Sass Transformer
  packages/configs/default/index.json
  packages/configs/default/package.json
  packages/core/integration-tests/test/integration/sass-advanced-import/package.json
  packages/core/integration-tests/test/integration/sass-include-paths-import/.sassrc.js
  packages/core/integration-tests/test/integration/sass-include-paths-import/include-path/style.sass
  packages/core/integration-tests/test/integration/sass-include-paths-import/index.sass
  packages/core/integration-tests/test/integration/sass-include-paths-import/package.json
  packages/core/integration-tests/test/integration/sass-node-modules-import/index.sass
  packages/core/integration-tests/test/integration/sass-node-modules-import/node_modules/library/package.json
  packages/core/integration-tests/test/integration/sass-node-modules-import/node_modules/library/style.sass
  packages/core/integration-tests/test/integration/sass-node-modules-import/package.json
  packages/core/integration-tests/test/integration/sass-webpack-import-error/index.sass
  packages/core/integration-tests/test/integration/sass-webpack-import-error/node_modules/library/style.sass
  packages/core/integration-tests/test/integration/sass-webpack-import-error/package.json
  packages/core/integration-tests/test/integration/scss-postcss/.postcssrc
  packages/core/integration-tests/test/integration/scss-postcss/index.js
  packages/core/integration-tests/test/integration/scss-postcss/index.module.scss
  packages/core/integration-tests/test/postcss.js
  packages/core/integration-tests/test/sass.js
  packages/core/parcel-bundler/src/utils/parseCSSImport.js
  packages/core/utils/src/parseCSSImport.js
  packages/transformers/sass/package.json
  packages/transformers/sass/src/SassTransformer.js
  yarn.lock
Labels: ✨ Parcel 2, 🔌 Parcel 2 Plugins

#3411 Fix autoinstall not using proper package names
  packages/core/install-package/src/installPackage.js
  packages/core/install-package/src/validateModuleSpecifiers.js
  packages/core/install-package/test/validateModuleSpecifiers.test.js
  yarn.lock
Labels: ✨ Parcel 2

#3422 Remove RequestGraph#addSubRequest
  packages/core/core/src/RequestGraph.js
Labels: ✨ Parcel 2

#3281 v2: Proxy table support
  packages/reporters/dev-server/package.json
  packages/reporters/dev-server/src/Server.js
  yarn.lock
Labels: ✨ Parcel 2

#3433 Proxy table/test
  packages/core/integration-tests/package.json
  packages/core/integration-tests/test/integration/proxyrc-js/.proxyrc.js
  packages/core/integration-tests/test/integration/proxyrc-js/index.js
  packages/core/integration-tests/test/integration/proxyrc-js/yarn.lock
  packages/core/integration-tests/test/integration/proxyrc/.proxyrc
  packages/core/integration-tests/test/integration/proxyrc/index.js
  packages/core/integration-tests/test/integration/proxyrc/yarn.lock
  packages/core/integration-tests/test/proxy.js
  packages/reporters/dev-server/src/Server.js
Labels: ✨ Parcel 2

#3440 Asset content cache keys
  packages/core/core/src/InternalAsset.js
  packages/core/core/src/Transformation.js
  packages/core/types/index.js
Labels: ✨ Parcel 2

#3445 Fix contributing alias work flow
  packages/core/core/src/ReporterRunner.js
  packages/core/core/src/resolveOptions.js
  packages/core/core/src/types.js
  packages/core/core/test/utils.js
  packages/core/parcel/src/cli.js
  packages/core/types/index.js
  packages/dev/babel-register/index.js
Labels: ✨ Parcel 2

#3149 Fix terser config and reenable some tests
  packages/core/integration-tests/test/javascript.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/optimizers/terser/src/TerserOptimizer.js
Labels: ✨ Parcel 2

#3457 refactor: Add yaml transformer and make test pass
  packages/configs/default/index.json
  packages/configs/default/package.json
  packages/core/integration-tests/test/javascript.js
  packages/transformers/yaml/package.json
  packages/transformers/yaml/src/YAMLTransformer.js
Labels: ✨ Parcel 2, 🔌 Parcel 2 Plugins

#3459 Remove eslint comments from prelude
  packages/shared/scope-hoisting/.eslintrc.json
  packages/shared/scope-hoisting/src/helpers.js
  packages/shared/scope-hoisting/src/prelude.js
Labels: ✨ Parcel 2

#3461 Use the same cache key for persisting initial asset
  packages/core/core/src/Transformation.js
Labels: ✨ Parcel 2

#3462 Add PugTransformer
  packages/configs/default/index.json
  packages/configs/default/package.json
  packages/core/integration-tests/test/integration/pug-include-extends/expect.html
  packages/core/integration-tests/test/integration/pug-locals/.pugrc
  packages/core/integration-tests/test/integration/pug-locals/index.pug
  packages/core/integration-tests/test/pug.js
  packages/transformers/pug/package.json
  packages/transformers/pug/src/PugTransformer.js
  yarn.lock
Labels: ✨ Parcel 2, 🔌 Parcel 2 Plugins

#3474 Improve sourceMappingURL matching to prevent false-positives
  .eslintignore
  packages/core/utils/src/loadSourceMapUrl.js
  packages/core/utils/test/input/sourcemap/inline.js
  packages/core/utils/test/input/sourcemap/no-sourcemap.js
  packages/core/utils/test/input/sourcemap/referenced.js
  packages/core/utils/test/loadSourceMapUrl.test.js
Labels: ✨ Parcel 2
