Repository parcel-bundler/parcel, pull requests merged in 2020-05, with the labels that each got.

#4578 Update the AssetGraph with a top down approach for more stable rebuilds
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/RequestTracker.js
  packages/core/core/src/requests/AssetRequestRunner.js
  packages/core/core/src/requests/DepPathRequestRunner.js
  packages/core/core/src/requests/EntryRequestRunner.js
  packages/core/core/src/requests/TargetRequestRunner.js
  packages/core/core/src/types.js
  packages/core/core/test/AssetGraph.test.js
Labels: :bug: Bug, ✨ Parcel 2

#4583 Apply CommonJS exports.foo assignments
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object/mutates.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object/value.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/link.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#4592 Reuse isDeferred from the bundle graph node, remove from dependency value
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/Dependency.js
  packages/core/core/src/dumpGraphToGraphViz.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/core/src/public/Dependency.js
  packages/core/core/src/types.js
  packages/core/types/index.js
  packages/shared/scope-hoisting/src/link.js
Labels: :bug: Bug, ✨ Parcel 2

#4558 Don't hardcode HMR hostname to localhost
  packages/core/parcel/src/cli.js
  packages/runtimes/hmr/src/loaders/hmr-runtime.js
Labels: :bug: Bug, ✨ Parcel 2

#4600 Fixup for #4583 (using AssignmentExpression outside ExpressionStatement)
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object-different/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object-different/mutates.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object-different/value.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object-expression/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object-expression/value.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object-importer/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object-importer/value.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/link.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#4591 Make BundleGraph parameterized on a particular Bundle type
  packages/core/core/src/BundlerRunner.js
  packages/core/core/src/PackagerRunner.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/applyRuntimes.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/core/src/public/MutableBundleGraph.js
  packages/core/test-utils/src/utils.js
  packages/core/types/index.js
  packages/core/utils/src/generateBuildMetrics.js
  packages/core/utils/src/relativeBundlePath.js
  packages/core/utils/src/replaceBundleReferences.js
  packages/packagers/html/src/HTMLPackager.js
  packages/packagers/js/src/JSPackager.js
  packages/reporters/bundle-analyzer/src/BundleAnalyzerReporter.js
  packages/reporters/cli/src/bundleReport.js
  packages/reporters/dev-server/src/Server.js
  packages/runtimes/js/src/JSRuntime.js
  packages/shared/scope-hoisting/src/concat.js
  packages/shared/scope-hoisting/src/formats/commonjs.js
  packages/shared/scope-hoisting/src/formats/esmodule.js
  packages/shared/scope-hoisting/src/formats/global.js
  packages/shared/scope-hoisting/src/generate.js
  packages/shared/scope-hoisting/src/link.js
  packages/shared/scope-hoisting/src/types.js
  packages/shared/scope-hoisting/src/utils.js
Labels: ✨ Parcel 2

#4604 Fix `getConfig` with `packageKey`
  packages/core/core/src/assetUtils.js
  packages/core/integration-tests/test/integration/postcss-config-package/package.json
  packages/core/integration-tests/test/integration/postcss-config-package/style.css
  packages/core/integration-tests/test/postcss.js
  packages/core/utils/src/config.js
  packages/core/utils/src/index.js
Labels: :bug: Bug, ✨ Parcel 2

#4610 Named export before decl generated wrong assignment order
  packages/core/integration-tests/test/integration/scope-hoisting/es6/export-before-declaration/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/export-before-declaration/b.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/hoist.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#4590 Never wrap sideEffect free assets
  packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-false-wrap-excluded/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-false-wrap-excluded/node_modules/bar/foo.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-false-wrap-excluded/node_modules/bar/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-false-wrap-excluded/node_modules/bar/other.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-false-wrap-excluded/node_modules/bar/package.json
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/concat.js
Labels: :bug: Bug, ✨ Parcel 2, 🌳 Tree Shaking

#4625 Use fs-write-stream-atomic to write atomic fs streams
  flow-libs/fs-write-stream-atomic.js.flow
  packages/core/core/src/PackagerRunner.js
  packages/core/fs/package.json
  packages/core/fs/src/MemoryFS.js
  packages/core/fs/src/NodeFS.js
  packages/core/is-v2-ready-yet/package.json
  packages/dev/eslint-config/package.json
  packages/dev/eslint-plugin/src/rules/no-self-package-imports.js
  yarn.lock
Labels: ✨ Parcel 2
