Repository parcel-bundler/parcel, pull requests merged in 2020-04, with the labels that each got.

#4409 Server: hold requests open during rebuilds
  packages/reporters/dev-server/src/Server.js
  packages/reporters/dev-server/src/ServerReporter.js
Labels: ✨ Parcel 2

#4416 Correct `addBundleImport`s with re-exports across bundle boundaries
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary-side-effects/async.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary-side-effects/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary-side-effects/switcher/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary-side-effects/switcher/package.json
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary-side-effects/types/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary/async.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary/switcher/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary/types/index.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/types/index.js
  packages/shared/scope-hoisting/src/link.js
Labels: :bug: Bug, 🌳 Tree Shaking

#4419 Fix test for isSubdirectory when resolving parcelrc in monorepo from cwd
  packages/core/core/src/loadParcelConfig.js
  packages/core/integration-tests/test/integration/custom-config/package.json
  packages/core/integration-tests/test/integration/parcelrc-custom/.parcelrc
  packages/core/integration-tests/test/integration/parcelrc-custom/configCopy
  packages/core/integration-tests/test/integration/parcelrc-custom/index.js
  packages/core/integration-tests/test/integration/parcelrc-custom/node_modules/parcel-transformer-do-nothing/index.js
  packages/core/integration-tests/test/integration/parcelrc-custom/node_modules/parcel-transformer-do-nothing/package.json
  packages/core/integration-tests/test/integration/parcelrc-custom/node_modules/parcel-transformer-mock/index.js
  packages/core/integration-tests/test/integration/parcelrc-custom/node_modules/parcel-transformer-mock/package.json
  packages/core/integration-tests/test/integration/parcelrc-custom/package.json
  packages/core/integration-tests/test/integration/parcelrc-custom/yarn.lock
  packages/core/integration-tests/test/integration/parcelrc-monorepo/app/.parcelrc
  packages/core/integration-tests/test/integration/parcelrc-monorepo/app/icon.svg
  packages/core/integration-tests/test/integration/parcelrc-monorepo/app/index.js
  packages/core/integration-tests/test/integration/parcelrc-monorepo/app/package.json
  packages/core/integration-tests/test/integration/parcelrc-monorepo/package.json
  packages/core/integration-tests/test/integration/parcelrc-monorepo/yarn.lock
  packages/core/integration-tests/test/monorepos.js
  packages/core/integration-tests/test/watcher.js
Labels: :bug: Bug

#4439 Upgrade to flow 0.122.0
  .flowconfig
  package.json
  yarn.lock
Labels: ✨ Parcel 2

#4391 Sync and async dependencies on the same module in the same bundle
  packages/bundlers/default/src/DefaultBundler.js
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/dumpGraphToGraphViz.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/core/src/public/MutableBundleGraph.js
  packages/core/integration-tests/test/integration/shared-exports-for-sibling-descendant/a.js
  packages/core/integration-tests/test/integration/shared-exports-for-sibling-descendant/b.js
  packages/core/integration-tests/test/integration/shared-exports-for-sibling-descendant/child.js
  packages/core/integration-tests/test/integration/shared-exports-for-sibling-descendant/grandchild.js
  packages/core/integration-tests/test/integration/shared-exports-for-sibling-descendant/index.js
  packages/core/integration-tests/test/integration/shared-exports-for-sibling-descendant/scope-hoisting.js
  packages/core/integration-tests/test/integration/shared-exports-for-sibling-descendant/wraps.js
  packages/core/integration-tests/test/integration/sync-async/dep.js
  packages/core/integration-tests/test/integration/sync-async/get-dep-2.js
  packages/core/integration-tests/test/integration/sync-async/get-dep-scope-hoisting.js
  packages/core/integration-tests/test/integration/sync-async/get-dep.js
  packages/core/integration-tests/test/integration/sync-async/same-ancestry-scope-hoisting.js
  packages/core/integration-tests/test/integration/sync-async/same-ancestry.js
  packages/core/integration-tests/test/integration/sync-async/same-bundle-scope-hoisting.js
  packages/core/integration-tests/test/integration/sync-async/same-bundle.js
  packages/core/integration-tests/test/javascript.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/test-utils/src/utils.js
  packages/core/types/index.js
  packages/core/utils/src/replaceBundleReferences.js
  packages/packagers/html/src/HTMLPackager.js
  packages/runtimes/js/src/JSRuntime.js
  packages/shared/scope-hoisting/src/concat.js
  packages/shared/scope-hoisting/src/link.js
  packages/shared/scope-hoisting/src/utils.js
Labels: ✨ Parcel 2

#4421 Share bundles when their entries exist in others
  packages/bundlers/default/src/DefaultBundler.js
  packages/core/core/src/public/MutableBundleGraph.js
  packages/core/integration-tests/test/html.js
  packages/core/integration-tests/test/integration/async-entry-shared/async.js
  packages/core/integration-tests/test/integration/async-entry-shared/index.js
  packages/core/integration-tests/test/integration/async-entry-shared/scope-hoisting.js
  packages/core/integration-tests/test/integration/async-entry-shared/value.js
  packages/core/integration-tests/test/integration/sync-entry-shared/async.js
  packages/core/integration-tests/test/integration/sync-entry-shared/index.js
  packages/core/integration-tests/test/integration/sync-entry-shared/value.js
  packages/core/integration-tests/test/javascript.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/types/index.js
  packages/runtimes/js/src/JSRuntime.js
  packages/shared/scope-hoisting/src/formats/global.js
  packages/shared/scope-hoisting/src/link.js
  packages/shared/scope-hoisting/src/utils.js
Labels: ✨ Parcel 2

#4447 Random fixes
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/integration-tests/test/babel.js
  packages/core/parcel/src/cli.js
Labels: :bug: Bug, ✨ Parcel 2

#4271 Remove crawl calls in shake & outputformat
  flow-libs/babel-traverse.js.flow
  packages/core/integration-tests/test/output-formats.js
  packages/shared/scope-hoisting/src/formats/commonjs.js
  packages/shared/scope-hoisting/src/formats/esmodule.js
  packages/shared/scope-hoisting/src/formats/global.js
  packages/shared/scope-hoisting/src/link.js
  packages/shared/scope-hoisting/src/shake.js
  packages/shared/scope-hoisting/src/types.js
  packages/shared/scope-hoisting/src/utils.js
Labels: :bullettrain_side: Performance, 🌳 Tree Shaking

#4456 Insert sibling bundles before main script with almost empty html
  packages/core/integration-tests/test/html.js
  packages/core/integration-tests/test/integration/html-js-shared-head/async.js
  packages/core/integration-tests/test/integration/html-js-shared-head/index.html
  packages/core/integration-tests/test/integration/html-js-shared-head/index.js
  packages/core/integration-tests/test/integration/html-js-shared-head/worker.js
  packages/core/integration-tests/test/integration/html-js-shared/async.js
  packages/core/integration-tests/test/integration/html-js-shared/index.html
  packages/core/integration-tests/test/integration/html-js-shared/index.js
  packages/core/integration-tests/test/integration/html-js-shared/worker.js
  packages/packagers/html/src/HTMLPackager.js
Labels: :bug: Bug

#4470 Fix requiring a nonentry asset from a sibling
  packages/core/integration-tests/test/integration/async-entry-shared-sibling/a.js
  packages/core/integration-tests/test/integration/async-entry-shared-sibling/b.js
  packages/core/integration-tests/test/integration/async-entry-shared-sibling/index.js
  packages/core/integration-tests/test/integration/async-entry-shared-sibling/other-entry.js
  packages/core/integration-tests/test/integration/async-entry-shared-sibling/scope-hoisting.js
  packages/core/integration-tests/test/integration/async-entry-shared-sibling/value.js
  packages/core/integration-tests/test/javascript.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/packagers/js/src/JSPackager.js
  packages/shared/scope-hoisting/src/generate.js
  packages/shared/scope-hoisting/src/link.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#4471 Fix shouldWrap race condition
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/core/src/public/MutableBundleGraph.js
  packages/core/types/index.js
  packages/packagers/js/src/JSPackager.js
  packages/shared/scope-hoisting/src/concat.js
  packages/shared/scope-hoisting/src/formats/global.js
  packages/shared/scope-hoisting/src/link.js
Labels: :bug: Bug, 🌳 Tree Shaking

#4473 Don't treeshake assignments to unknown objects
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/tree-shaking-no-unknown-objects/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/tree-shaking-no-unknown-objects/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-no-unknown-objects/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-no-unknown-objects/index.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/link.js
  packages/shared/scope-hoisting/src/shake.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#4467 Fix resolveSymbol when working across bundle boundary
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/public/Asset.js
  packages/core/core/src/public/Dependency.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary2/async.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary2/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary2/library/components.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary2/library/constants.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary2/library/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary3/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary3/media-card/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary3/theme/components.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary3/theme/createTheme.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary3/theme/index.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/dev/babel-preset/index.js
Labels: :bug: Bug, 🌳 Tree Shaking

#4440 CSS SourceMaps
  flow-libs/postcss.js.flow
  packages/core/cache/src/Cache.js
  packages/core/core/src/utils.js
  packages/core/integration-tests/test/css.js
  packages/core/integration-tests/test/html.js
  packages/core/integration-tests/test/integration/sourcemap-css-import/package.json
  packages/core/integration-tests/test/integration/sourcemap-css-import/yarn.lock
  packages/core/integration-tests/test/integration/sourcemap-css/package.json
  packages/core/integration-tests/test/integration/sourcemap-css/yarn.lock
  packages/core/integration-tests/test/integration/sourcemap-less/package.json
  packages/core/integration-tests/test/integration/sourcemap-less/yarn.lock
  packages/core/integration-tests/test/integration/sourcemap-sass-imported/package.json
  packages/core/integration-tests/test/integration/sourcemap-sass-imported/yarn.lock
  packages/core/integration-tests/test/integration/sourcemap-sass/package.json
  packages/core/integration-tests/test/integration/sourcemap-sass/yarn.lock
  packages/core/integration-tests/test/integration/sourcemap-typescript-nested/package.json
  packages/core/integration-tests/test/integration/sourcemap-typescript-nested/yarn.lock
  packages/core/integration-tests/test/integration/sourcemap-typescript/package.json
  packages/core/integration-tests/test/integration/sourcemap-typescript/yarn.lock
  packages/core/integration-tests/test/javascript.js
  packages/core/integration-tests/test/less.js
  packages/core/integration-tests/test/sass.js
  packages/core/integration-tests/test/sourcemaps.js
  packages/core/register/src/register.js
  packages/core/test-utils/src/utils.js
  packages/core/utils/src/index.js
  packages/core/utils/src/schema.js
  packages/optimizers/cssnano/package.json
  packages/optimizers/cssnano/src/CSSNanoOptimizer.js
  packages/optimizers/htmlnano/src/HTMLNanoOptimizer.js
  packages/packagers/css/package.json
  packages/packagers/css/src/CSSPackager.js
  packages/packagers/js/src/JSPackager.js
  packages/transformers/css/package.json
  packages/transformers/css/src/CSSTransformer.js
Labels: ✨ Parcel 2

#4438 Babel envName: Consider process.env.BABEL_ENV and process.env.NODE_ENV
  packages/core/integration-tests/test/babel.js
  packages/core/integration-tests/test/integration/babel-env-name/.babelrc
  packages/core/integration-tests/test/integration/babel-env-name/index.js
  packages/transformers/babel/src/config.js
Labels: ✨ Parcel 2, 🔌 Parcel 2 Plugins

#4397 Feature/v2 jsonld transformer
  packages/configs/default/index.json
  packages/configs/default/package.json
  packages/core/integration-tests/test/schema-jsonld.js
  packages/packagers/html/src/HTMLPackager.js
  packages/packagers/raw-url/package.json
  packages/packagers/raw-url/src/RawUrlPackager.js
  packages/transformers/jsonld/package.json
  packages/transformers/jsonld/src/JSONLDTransformer.js
Labels: 🔌 Parcel 2 Plugins

#4496 removeBundleGroup: Only remove bundles entirely if they are only part of this group
  packages/core/core/src/public/MutableBundleGraph.js
Labels: ✨ Parcel 2

#4295 Fix assets duplicated between sibling bundles, and parallel request limit behavior
  packages/bundlers/default/src/DefaultBundler.js
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/applyRuntimes.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/core/src/public/MutableBundleGraph.js
  packages/core/integration-tests/test/html.js
  packages/core/integration-tests/test/integration/shared-many/a.html
  packages/core/integration-tests/test/integration/shared-many/a.js
  packages/core/integration-tests/test/integration/shared-many/b.html
  packages/core/integration-tests/test/integration/shared-many/b.js
  packages/core/integration-tests/test/integration/shared-many/c.html
  packages/core/integration-tests/test/integration/shared-many/c.js
  packages/core/integration-tests/test/integration/shared-many/d.html
  packages/core/integration-tests/test/integration/shared-many/d.js
  packages/core/integration-tests/test/integration/shared-many/e.html
  packages/core/integration-tests/test/integration/shared-many/e.js
  packages/core/integration-tests/test/integration/shared-many/f.html
  packages/core/integration-tests/test/integration/shared-many/f.js
  packages/core/integration-tests/test/integration/shared-many/g.html
  packages/core/integration-tests/test/integration/shared-many/g.js
  packages/core/integration-tests/test/integration/shared-sibling-duplicate/a.html
  packages/core/integration-tests/test/integration/shared-sibling-duplicate/a.js
  packages/core/integration-tests/test/integration/shared-sibling-duplicate/b.html
  packages/core/integration-tests/test/integration/shared-sibling-duplicate/b.js
  packages/core/integration-tests/test/integration/shared-sibling-duplicate/c.html
  packages/core/integration-tests/test/integration/shared-sibling-duplicate/c.js
  packages/core/types/index.js
Labels: :bug: Bug

#4533 JSRuntime: take URL of last bundle in bundle group
  packages/core/integration-tests/package.json
  packages/core/integration-tests/test/integration/html-shared-worker/index.js
  packages/core/integration-tests/test/integration/html-shared-worker/worker.js
  packages/core/integration-tests/test/javascript.js
  packages/core/integration-tests/test/typescript.js
  packages/core/test-utils/src/utils.js
  packages/runtimes/js/src/JSRuntime.js
  packages/runtimes/js/src/bundle-url.js
Labels: :bug: Bug

#4493 addDependency: update `symbols`
  packages/core/core/src/AssetGraph.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/cache-add-specifier/a.1.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/cache-add-specifier/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/cache-add-specifier/b.js
  packages/core/integration-tests/test/scope-hoisting.js
Labels: :bug: Bug

#4545 Import asset from reachable bundle in ESM output format
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/integration-tests/test/html.js
  packages/core/integration-tests/test/integration/shared-many-esm/a.html
  packages/core/integration-tests/test/integration/shared-many-esm/a.js
  packages/core/integration-tests/test/integration/shared-many-esm/b.html
  packages/core/integration-tests/test/integration/shared-many-esm/b.js
  packages/core/integration-tests/test/integration/shared-many-esm/c.html
  packages/core/integration-tests/test/integration/shared-many-esm/c.js
  packages/core/integration-tests/test/integration/shared-many-esm/d.html
  packages/core/integration-tests/test/integration/shared-many-esm/d.js
  packages/core/integration-tests/test/integration/shared-many-esm/e.html
  packages/core/integration-tests/test/integration/shared-many-esm/e.js
  packages/core/integration-tests/test/integration/shared-many-esm/f.html
  packages/core/integration-tests/test/integration/shared-many-esm/f.js
  packages/core/integration-tests/test/integration/shared-many-esm/g.html
  packages/core/integration-tests/test/integration/shared-many-esm/g.js
  packages/core/types/index.js
  packages/shared/scope-hoisting/src/link.js
Labels: :bug: Bug
