Repository parcel-bundler/parcel, pull requests merged in 2020-03, with the labels that each got.

#4267 Make ParcelOptions a shared reference in workers
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/PackagerRunner.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/requests.js
  packages/core/core/src/types.js
  packages/core/core/src/worker.js
  packages/core/core/test/AssetGraphBuilder.test.js
Labels: ✨ Parcel 2

#4280 Fix `pkg#alias` on Windows and make asset hash more stable
  packages/core/core/src/Transformation.js
  packages/core/core/src/Validation.js
  packages/core/integration-tests/test/integration/alias/bar.js
  packages/core/integration-tests/test/integration/alias/exclude-local.js
  packages/core/integration-tests/test/integration/alias/exclude-package.js
  packages/core/integration-tests/test/integration/alias/package-to-local.js
  packages/core/integration-tests/test/integration/alias/package-to-package.js
  packages/core/integration-tests/test/integration/alias/package.json
  packages/core/integration-tests/test/resolver.js
  packages/utils/node-resolver-core/src/NodeResolver.js
Labels: ✨ Parcel 2

#4306 Insert sibling bundles after doctype
  packages/core/integration-tests/test/html.js
  packages/core/integration-tests/test/integration/html-css-doctype/index.css
  packages/core/integration-tests/test/integration/html-css-doctype/index.html
  packages/core/integration-tests/test/integration/html-css-doctype/index.js
  packages/packagers/html/src/HTMLPackager.js
Labels: :bug: Bug

#4325 Upgrade to flow 0.120.1
  .flowconfig
  package.json
  yarn.lock
Labels: ✨ Parcel 2

#4279 Bailout exports.foo resolving when exports is used freely
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/exports-assign.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/exports-define.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/module-exports-assign.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/module-exports-define.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/hoist.js
  packages/shared/scope-hoisting/src/link.js
  packages/shared/scope-hoisting/src/shake.js
Labels: :bug: Bug, 🌳 Tree Shaking

#4339 Don't overwrite already installed version when autoinstalling peer dependencies
  packages/core/package-manager/src/NodePackageManager.js
  packages/core/package-manager/src/installPackage.js
  packages/core/package-manager/src/utils.js
  packages/core/package-manager/test/NodePackageManager.test.js
  packages/core/package-manager/test/fixtures/empty/package.json
  packages/core/package-manager/test/fixtures/packages/peers-2.0/index.js
  packages/core/package-manager/test/fixtures/packages/peers-2.0/package.json
  packages/core/package-manager/test/fixtures/packages/peers/index.js
  packages/core/package-manager/test/fixtures/packages/peers/package.json
Labels: :bug: Bug

#4309 Load async and shared bundle in worker
  packages/core/integration-tests/test/integration/formats/esm-split-worker/async.js
  packages/core/integration-tests/test/integration/formats/esm-split-worker/index.html
  packages/core/integration-tests/test/integration/formats/esm-split-worker/index.js
  packages/core/integration-tests/test/integration/formats/esm-split-worker/main-worker.js
  packages/core/integration-tests/test/integration/formats/esm-split-worker/sync.js
  packages/core/integration-tests/test/integration/formats/global-split-worker/async.js
  packages/core/integration-tests/test/integration/formats/global-split-worker/index.html
  packages/core/integration-tests/test/integration/formats/global-split-worker/index.js
  packages/core/integration-tests/test/integration/formats/global-split-worker/main-worker.js
  packages/core/integration-tests/test/integration/formats/global-split-worker/sync.js
  packages/core/integration-tests/test/output-formats.js
  packages/runtimes/js/src/JSRuntime.js
  packages/runtimes/js/src/loaders/worker/js-loader.js
  packages/runtimes/js/src/loaders/worker/wasm-loader.js
Labels: :bug: Bug

#4355 Instantiate shared references after child worker is initialized
  packages/core/workers/src/Worker.js
  packages/core/workers/src/WorkerFarm.js
Labels: :bug: Bug

#4266 [T-373] Fix importing wrapped assets from a different bundle
  packages/core/integration-tests/test/integration/formats/commonjs-wrap-codesplit/a.js
  packages/core/integration-tests/test/integration/formats/commonjs-wrap-codesplit/b.js
  packages/core/integration-tests/test/integration/formats/commonjs-wrap-codesplit/c.js
  packages/core/integration-tests/test/integration/formats/commonjs-wrap-codesplit/package.json
  packages/core/integration-tests/test/integration/formats/commonjs-wrap-codesplit/yarn.lock
  packages/core/integration-tests/test/integration/formats/esm-wrap-codesplit/a.js
  packages/core/integration-tests/test/integration/formats/esm-wrap-codesplit/b.js
  packages/core/integration-tests/test/integration/formats/esm-wrap-codesplit/c.js
  packages/core/integration-tests/test/integration/formats/esm-wrap-codesplit/package.json
  packages/core/integration-tests/test/integration/formats/esm-wrap-codesplit/yarn.lock
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-module-codesplit/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-module-codesplit/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-module-codesplit/c.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-wrapped/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-wrapped/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-wrapped/c.js
  packages/core/integration-tests/test/output-formats.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/test-utils/src/utils.js
  packages/shared/scope-hoisting/src/concat.js
  packages/shared/scope-hoisting/src/formats/commonjs.js
  packages/shared/scope-hoisting/src/formats/esmodule.js
  packages/shared/scope-hoisting/src/formats/global.js
  packages/shared/scope-hoisting/src/link.js
  packages/shared/scope-hoisting/src/shake.js
Labels: :bug: Bug, 🌳 Tree Shaking

#3730 Fix code splitting with interop shared bundle
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split-intermediate/import.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split-intermediate/import_child.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split-intermediate/main.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split-intermediate/main_child.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split-intermediate/shared.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split-intermediate/shared_sub.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split/import.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split/main.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split/shared.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split/shared_sub.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/types/index.js
  packages/shared/scope-hoisting/src/concat.js
  packages/shared/scope-hoisting/src/link.js
Labels: :bug: Bug, 🌳 Tree Shaking

#4275 Fix concat order
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/concat-order/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/concat-order/b.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/concat.js
Labels: :bug: Bug, 🌳 Tree Shaking

#4249 Fix bug when exporting a binding multiple times
  packages/core/integration-tests/test/integration/formats/esm-commonjs/multiple-times.js
  packages/core/integration-tests/test/integration/formats/esm/multiple-times.js
  packages/core/integration-tests/test/output-formats.js
  packages/shared/scope-hoisting/src/formats/commonjs.js
  packages/shared/scope-hoisting/src/formats/esmodule.js
Labels: :bug: Bug, 🌳 Tree Shaking

#4288 Concat order for globals is wrong
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/concat-order-globals/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/concat-order-globals/b.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/test-utils/src/utils.js
  packages/shared/scope-hoisting/src/concat.js
  packages/transformers/js/src/JSTransformer.js
  packages/transformers/js/src/visitors/fs.js
Labels: :bug: Bug, 🌳 Tree Shaking

#4369 Fix worker crash
  packages/core/core/src/summarizeRequest.js
  packages/core/utils/src/md5.js
Labels: :bug: Bug

#4371 Fix validation of removed files
  packages/core/core/src/AssetGraphBuilder.js
Labels: :bug: Bug

#4370 T-404 Don't query asset.meta.shouldWrap in packager, create fake init instead
  packages/core/integration-tests/test/output-formats.js
  packages/shared/scope-hoisting/src/formats/commonjs.js
  packages/shared/scope-hoisting/src/formats/esmodule.js
  packages/shared/scope-hoisting/src/formats/global.js
  packages/shared/scope-hoisting/src/link.js
Labels: :bug: Bug, :memo: WIP, 🌳 Tree Shaking

#4281 T-398 Source Map Performance enhancements
  packages/core/core/package.json
  packages/core/core/src/InternalAsset.js
  packages/core/core/src/Transformation.js
  packages/core/core/src/public/Asset.js
  packages/core/integration-tests/test/sourcemaps.js
  packages/core/source-map/package.json
  packages/core/source-map/src/SourceMap.js
  packages/core/source-map/test/add-map.test.js
  packages/core/source-map/test/extend-sourcemap.test.js
  packages/core/source-map/test/get-positions-sourcemap.test.js
  packages/core/types/index.js
  packages/examples/kitchen-sink/package.json
  packages/optimizers/terser/package.json
  packages/optimizers/terser/src/TerserOptimizer.js
  packages/packagers/js/package.json
  packages/packagers/js/src/JSPackager.js
  packages/transformers/babel/package.json
  packages/transformers/babel/src/BabelTransformer.js
  packages/transformers/coffeescript/package.json
  packages/transformers/coffeescript/src/CoffeeScriptTransformer.js
  packages/transformers/js/package.json
  packages/transformers/js/src/JSTransformer.js
  packages/transformers/react-refresh-wrap/package.json
  packages/transformers/react-refresh-wrap/src/ReactRefreshWrapTransformer.js
  packages/transformers/typescript-types/package.json
  packages/transformers/typescript-types/src/TSTypesTransformer.js
  yarn.lock
Labels: :bullettrain_side: Performance

#4381 Upgrade to flow 0.121.0
  .flowconfig
  flow-libs/posthtml.js.flow
  package.json
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/InternalAsset.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/RequestTracker.js
  packages/core/core/src/loadDotEnv.js
  packages/core/core/src/loadParcelConfig.js
  packages/core/core/src/public/Environment.js
  packages/core/core/src/resolveOptions.js
  packages/core/core/src/worker.js
  packages/core/core/test/loadParcelConfig.test.js
  packages/core/logger/src/Logger.js
  packages/core/utils/src/glob.js
  packages/core/workers/src/WorkerFarm.js
  packages/core/workers/src/child.js
  packages/core/workers/src/cpuCount.js
  packages/optimizers/cssnano/src/CSSNanoOptimizer.js
  packages/packagers/css/src/CSSPackager.js
  packages/transformers/babel/src/BabelTransformer.js
  packages/transformers/html/src/inline.js
  packages/transformers/js/src/visitors/fs.js
  packages/transformers/postcss/src/PostCSSTransformer.js
  packages/utils/node-resolver-core/src/NodeResolver.js
  yarn.lock
Labels: ✨ Parcel 2

#4282 Hoist all "top-level" var declarations when wrapping a module
  flow-libs/babel-traverse.js.flow
  flow-libs/babel-types.js.flow
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-var-hoisting/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-var-hoisting/b.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/concat.js
  packages/transformers/js/src/visitors/dependencies.js
  packages/utils/babylon-walk/README.md
  packages/utils/babylon-walk/src/explode.js
  packages/utils/babylon-walk/src/index.js
  packages/utils/babylon-walk/src/traverse.js
Labels: :bug: Bug, 🌳 Tree Shaking

#4385 Scope hoisting: async bundles named-importing a re-exported namespace
  packages/core/integration-tests/test/integration/scope-hoisting/es6/async-named-import-ns-reexport/async.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/async-named-import-ns-reexport/index.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/async-named-import-ns-reexport/ns.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/async-named-import-ns-reexport/reexports.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/link.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#4378 Split InternalAsset into UncommittedAsset and CommittedAsset (Cache ASTs followup)
  packages/core/core/src/CommittedAsset.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/Transformation.js
  packages/core/core/src/UncommittedAsset.js
  packages/core/core/src/Validation.js
  packages/core/core/src/assetUtils.js
  packages/core/core/src/public/Asset.js
  packages/core/core/src/public/Bundle.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/core/src/public/MutableBundleGraph.js
  packages/core/core/src/types.js
  packages/core/core/test/AssetGraph.test.js
  packages/core/core/test/InternalAsset.test.js
  packages/core/core/test/PublicAsset.test.js
  packages/transformers/babel/package.json
  packages/transformers/babel/src/babel7.js
Labels: ✨ Parcel 2
