Repository parcel-bundler/parcel, pull requests merged in 2020-06, with the labels that each got.

#4685 Vendor fs write stream atomic
  .eslintignore
  .gitignore
  .mocharc.json
  packages/core/fs/package.json
  packages/core/fs/src/NodeFS.js
  packages/utils/fs-write-stream-atomic/.travis.yml
  packages/utils/fs-write-stream-atomic/LICENSE
  packages/utils/fs-write-stream-atomic/README.md
  packages/utils/fs-write-stream-atomic/fixtures/thread-id-test-worker.js
  packages/utils/fs-write-stream-atomic/index.js
  packages/utils/fs-write-stream-atomic/package.json
  packages/utils/fs-write-stream-atomic/test/basic.js
  packages/utils/fs-write-stream-atomic/test/chown.js
  packages/utils/fs-write-stream-atomic/test/rename-eperm.js
  packages/utils/fs-write-stream-atomic/test/rename-fail.js
  packages/utils/fs-write-stream-atomic/test/slow-close.js
  packages/utils/fs-write-stream-atomic/test/thread-id.js
  packages/utils/fs-write-stream-atomic/test/toolong.js
  packages/utils/fs-write-stream-atomic/thread-id.js
  yarn.lock
Labels: ✨ Parcel 2

#4690 Terser: also mangle toplevel with commonjs
  packages/optimizers/terser/src/TerserOptimizer.js
Labels: ✨ Parcel 2

#4701 Replace toplevel `this` with `undefined` in ESM assets
  packages/core/integration-tests/test/integration/js-this-commonjs/a.js
  packages/core/integration-tests/test/integration/js-this-commonjs/b.js
  packages/core/integration-tests/test/integration/js-this-es6/a.js
  packages/core/integration-tests/test/integration/js-this-es6/b.js
  packages/core/integration-tests/test/javascript.js
  packages/shared/scope-hoisting/src/hoist.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#4694 Fix chained namespace reexports
  packages/core/core/src/BundleGraph.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-chained/.babelrc
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-chained/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-chained/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-chained/c1.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-chained/c2.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-chained/d.js
  packages/core/integration-tests/test/scope-hoisting.js
Labels: ✨ Parcel 2, 🌳 Tree Shaking

#4752 T-345 use loadconfig for posthtml
  packages/core/core/src/Transformation.js
  packages/core/integration-tests/test/html.js
  packages/core/integration-tests/test/pug.js
  packages/core/parcel/README.md
  packages/core/types/index.js
  packages/transformers/posthtml/src/PostHTMLTransformer.js
Labels: ✨ Parcel 2

#4754 Fix reverse handles
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/fs/src/MemoryFS.js
  packages/core/workers/src/Handle.js
  packages/core/workers/src/WorkerFarm.js
  packages/core/workers/src/child.js
  packages/core/workers/test/integration/workerfarm/reverse-handle.js
Labels: :bug: Bug, ✨ Parcel 2

#4767 PnP: Support importing builtins from npm with `assert/`
  packages/core/integration-tests/test/integration/pnp-builtin/.pnp.js
  packages/core/integration-tests/test/integration/pnp-builtin/index.js
  packages/core/integration-tests/test/integration/pnp-builtin/local.js
  packages/core/integration-tests/test/integration/pnp-builtin/pnp/module/index.js
  packages/core/integration-tests/test/pnp.js
  packages/utils/node-resolver-core/src/NodeResolver.js
Labels: :bug: Bug, ✨ Parcel 2

#4745 Adding support for <amp-img src=”path/to/img.jpg”>
  packages/transformers/html/src/dependencies.js
Labels: ✨ Parcel 2

#4759 Fix named imports of CommonJS assets with namespace exports via namespace reexports
  packages/core/core/src/BundleGraph.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-commonjs-wildcard/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-commonjs-wildcard/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-commonjs-wildcard/c.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-commonjs-wildcard/d.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/link.js
Labels: :bug: Bug, ✨ Parcel 2, 🌳 Tree Shaking

#4650 Support subrequests in RequestTracker
  packages/core/core/src/AssetGraph.js
  packages/core/core/src/AssetGraphBuilder.js
  packages/core/core/src/Graph.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/RequestTracker.js
  packages/core/core/src/Transformation.js
  packages/core/core/src/Validation.js
  packages/core/core/src/applyRuntimes.js
  packages/core/core/src/requests/AssetRequest.js
  packages/core/core/src/requests/AssetRequestRunner.js
  packages/core/core/src/requests/DepPathRequestRunner.js
  packages/core/core/src/requests/EntryRequest.js
  packages/core/core/src/requests/EntryRequestRunner.js
  packages/core/core/src/requests/ParcelConfigRequest.js
  packages/core/core/src/requests/ParcelConfigRequestRunner.js
  packages/core/core/src/requests/PathRequest.js
  packages/core/core/src/requests/TargetRequest.js
  packages/core/core/src/requests/TargetRequestRunner.js
  packages/core/core/src/summarizeRequest.js
  packages/core/core/src/types.js
  packages/core/core/src/worker.js
  packages/core/core/test/AssetGraphBuilder.test.js
  packages/core/core/test/RequestTracker.test.js
  packages/core/core/test/requests/ParcelConfigRequest.test.js
  packages/core/core/test/requests/TargetRequest.test.js
  packages/core/fs/src/MemoryFS.js
Labels: ✨ Parcel 2

#4805 Remove empty bundles and bundle groups
  packages/core/core/src/BundleGraph.js
Labels: :bug: Bug, ✨ Parcel 2
