Repository parcel-bundler/parcel, pull requests merged in 2021-01, with the labels that each got.

#5440 Don't loadConfig the root package.json for every package
  packages/core/core/src/PackagerRunner.js
  packages/core/core/src/Parcel.js
  packages/core/core/src/worker.js
  packages/core/package-manager/test/NodePackageManager.test.js
  packages/core/utils/package.json
  packages/core/utils/src/config.js
  yarn.lock
Labels: :bullettrain_side: Performance

#5432 Improve performance of printing JS ASTs
  packages/core/integration-tests/test/babel.js
  packages/core/integration-tests/test/hmr.js
  packages/core/integration-tests/test/html.js
  packages/core/integration-tests/test/integration/jsx-react/pure-comment.js
  packages/core/integration-tests/test/output-formats.js
  packages/shared/babel-ast-utils/package.json
  packages/shared/babel-ast-utils/src/generator.js
  packages/shared/babel-ast-utils/src/index.js
  packages/shared/babel-ast-utils/test/fixtures/array.js
  packages/shared/babel-ast-utils/test/fixtures/async.js
  packages/shared/babel-ast-utils/test/fixtures/await.js
  packages/shared/babel-ast-utils/test/fixtures/call.js
  packages/shared/babel-ast-utils/test/fixtures/class.js
  packages/shared/babel-ast-utils/test/fixtures/control.js
  packages/shared/babel-ast-utils/test/fixtures/error.js
  packages/shared/babel-ast-utils/test/fixtures/export-class.js
  packages/shared/babel-ast-utils/test/fixtures/export-function.js
  packages/shared/babel-ast-utils/test/fixtures/export.js
  packages/shared/babel-ast-utils/test/fixtures/function.js
  packages/shared/babel-ast-utils/test/fixtures/import.js
  packages/shared/babel-ast-utils/test/fixtures/literal.js
  packages/shared/babel-ast-utils/test/fixtures/loop.js
  packages/shared/babel-ast-utils/test/fixtures/number.js
  packages/shared/babel-ast-utils/test/fixtures/object.js
  packages/shared/babel-ast-utils/test/fixtures/operators.js
  packages/shared/babel-ast-utils/test/fixtures/precedence.js
  packages/shared/babel-ast-utils/test/fixtures/sequence.js
  packages/shared/babel-ast-utils/test/fixtures/template.js
  packages/shared/babel-ast-utils/test/fixtures/variable.js
  packages/shared/babel-ast-utils/test/index.js
  packages/shared/scope-hoisting/package.json
  packages/shared/scope-hoisting/src/generate.js
  packages/transformers/babel/package.json
  packages/transformers/js/package.json
  packages/transformers/react-refresh-wrap/package.json
  yarn.lock
Labels: :bullettrain_side: Performance

#4815 Make scope hoisting linker ~25x faster
  flow-libs/babel-types.js.flow
  packages/core/core/src/BundleGraph.js
  packages/core/core/src/Dependency.js
  packages/core/core/src/assetUtils.js
  packages/core/core/src/public/Bundle.js
  packages/core/core/src/public/BundleGraph.js
  packages/core/core/src/public/Symbols.js
  packages/core/core/src/requests/AssetGraphRequest.js
  packages/core/core/src/types.js
  packages/core/integration-tests/test/integration/formats/commonjs-entry-re-export/a.js
  packages/core/integration-tests/test/integration/formats/commonjs-entry-re-export/b.js
  packages/core/integration-tests/test/integration/formats/commonjs-entry-re-export/package.json
  packages/core/integration-tests/test/integration/formats/commonjs-entry-re-export/yarn.lock
  packages/core/integration-tests/test/integration/formats/commonjs-esm-entry-re-export/a.js
  packages/core/integration-tests/test/integration/formats/commonjs-esm-entry-re-export/b.js
  packages/core/integration-tests/test/integration/formats/commonjs-esm-entry-re-export/package.json
  packages/core/integration-tests/test/integration/formats/commonjs-esm-entry-re-export/yarn.lock
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-self-reference/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-self-reference/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-self-reference/package.json
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-self-reference/yarn.lock
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-commonjs/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-commonjs/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/module-exports-self-reference/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/module-exports-self-reference/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/module-exports-self-reference/package.json
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/module-exports-self-reference/yarn.lock
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/non-static-exports/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/non-static-exports/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/require-assign/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/require-assign/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/require-member-wrapped/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/require-member-wrapped/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/require-member-wrapped/c.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/require-multiple/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/require-multiple/b.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/require-multiple/c.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/self-reference-assignment/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/self-reference-default/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/commonjs/self-reference-default/b.js
  packages/core/integration-tests/test/output-formats.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/core/types/index.js
  packages/packagers/js/src/JSPackager.js
  packages/shared/scope-hoisting/package.json
  packages/shared/scope-hoisting/src/concat.js
  packages/shared/scope-hoisting/src/formats/commonjs.js
  packages/shared/scope-hoisting/src/formats/esmodule.js
  packages/shared/scope-hoisting/src/formats/global.js
  packages/shared/scope-hoisting/src/hoist.js
  packages/shared/scope-hoisting/src/index.js
  packages/shared/scope-hoisting/src/link.js
  packages/shared/scope-hoisting/src/shake.js
  packages/shared/scope-hoisting/src/types.js
  packages/shared/scope-hoisting/src/utils.js
  packages/utils/babylon-walk/src/scope.js
  yarn.lock
Labels: :bullettrain_side: Performance, 🌳 Tree Shaking

#5664 Add interop declaration for ESM cross bundle imports
  packages/core/integration-tests/test/integration/formats/esm-interop-cross-bundle/a.js
  packages/core/integration-tests/test/integration/formats/esm-interop-cross-bundle/b.js
  packages/core/integration-tests/test/integration/formats/esm-interop-cross-bundle/c.js
  packages/core/integration-tests/test/integration/formats/esm-interop-cross-bundle/package.json
  packages/core/integration-tests/test/integration/formats/esm-interop-cross-bundle/yarn.lock
  packages/core/integration-tests/test/output-formats.js
  packages/shared/scope-hoisting/src/formats/esmodule.js
Labels: 🌳 Tree Shaking

#5485 Improve getHintedBundleGroups performance in JSRuntime
  packages/runtimes/js/src/JSRuntime.js
Labels: :bullettrain_side: Performance

#5689 Fix default exports of JS globals
  packages/core/integration-tests/test/integration/scope-hoisting/es6/export-default-js-global/a.js
  packages/core/integration-tests/test/integration/scope-hoisting/es6/export-default-js-global/b.js
  packages/core/integration-tests/test/scope-hoisting.js
  packages/shared/scope-hoisting/src/hoist.js
Labels: 🌳 Tree Shaking
